package org.uddi.v3_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-07T19:55:12.111+01:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebServiceClient(name = "UDDIInquiryService", 
                  wsdlLocation = "http://localhost:8081/juddiv3/services/inquiry?wsdl",
                  targetNamespace = "urn:uddi-org:v3_service") 
public class UDDIInquiryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:uddi-org:v3_service", "UDDIInquiryService");
    public final static QName UDDIInquiryImplPort = new QName("urn:uddi-org:v3_service", "UDDIInquiryImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/juddiv3/services/inquiry?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UDDIInquiryService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/juddiv3/services/inquiry?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UDDIInquiryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UDDIInquiryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UDDIInquiryService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UDDIInquiryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UDDIInquiryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UDDIInquiryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns UDDIInquiryPortType
     */
    @WebEndpoint(name = "UDDIInquiryImplPort")
    public UDDIInquiryPortType getUDDIInquiryImplPort() {
        return super.getPort(UDDIInquiryImplPort, UDDIInquiryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UDDIInquiryPortType
     */
    @WebEndpoint(name = "UDDIInquiryImplPort")
    public UDDIInquiryPortType getUDDIInquiryImplPort(WebServiceFeature... features) {
        return super.getPort(UDDIInquiryImplPort, UDDIInquiryPortType.class, features);
    }

}
