
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.uddi.v3_service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-07T19:55:11.983+01:00
 * Generated source version: 3.0.0-milestone1
 * 
 */

@javax.jws.WebService(
                      serviceName = "UDDIInquiryService",
                      portName = "UDDIInquiryImplPort",
                      targetNamespace = "urn:uddi-org:v3_service",
                      wsdlLocation = "http://localhost:8081/juddiv3/services/inquiry?wsdl",
                      endpointInterface = "org.uddi.v3_service.UDDIInquiryPortType")
                      
public class UDDIInquiryPortTypeImpl implements UDDIInquiryPortType {

    private static final Logger LOG = Logger.getLogger(UDDIInquiryPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#getTModelDetail(org.uddi.api_v3.GetTModelDetail  body )*
     */
    public org.uddi.api_v3.TModelDetail getTModelDetail(org.uddi.api_v3.GetTModelDetail body) { 
        LOG.info("Executing operation getTModelDetail");
        System.out.println(body);
        try {
            org.uddi.api_v3.TModelDetail _return = new org.uddi.api_v3.TModelDetail();
            java.util.List<org.uddi.api_v3.TModel> _returnTModel = new java.util.ArrayList<org.uddi.api_v3.TModel>();
            org.uddi.api_v3.TModel _returnTModelVal1 = new org.uddi.api_v3.TModel();
            org.uddi.api_v3.Name _returnTModelVal1Name = new org.uddi.api_v3.Name();
            _returnTModelVal1Name.setValue("Value-1344445100");
            _returnTModelVal1Name.setLang("Lang-392859577");
            _returnTModelVal1.setName(_returnTModelVal1Name);
            java.util.List<org.uddi.api_v3.Description> _returnTModelVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
            _returnTModelVal1.getDescription().addAll(_returnTModelVal1Description);
            java.util.List<org.uddi.api_v3.OverviewDoc> _returnTModelVal1OverviewDoc = new java.util.ArrayList<org.uddi.api_v3.OverviewDoc>();
            _returnTModelVal1.getOverviewDoc().addAll(_returnTModelVal1OverviewDoc);
            org.uddi.api_v3.IdentifierBag _returnTModelVal1IdentifierBag = new org.uddi.api_v3.IdentifierBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnTModelVal1IdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnTModelVal1IdentifierBag.getKeyedReference().addAll(_returnTModelVal1IdentifierBagKeyedReference);
            _returnTModelVal1.setIdentifierBag(_returnTModelVal1IdentifierBag);
            org.uddi.api_v3.CategoryBag _returnTModelVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnTModelVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnTModelVal1CategoryBag.getKeyedReference().addAll(_returnTModelVal1CategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnTModelVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnTModelVal1CategoryBag.getKeyedReferenceGroup().addAll(_returnTModelVal1CategoryBagKeyedReferenceGroup);
            _returnTModelVal1.setCategoryBag(_returnTModelVal1CategoryBag);
            java.util.List<org.w3._2000._09.xmldsig.SignatureType> _returnTModelVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
            _returnTModelVal1.getSignature().addAll(_returnTModelVal1Signature);
            _returnTModelVal1.setTModelKey("TModelKey264609897");
            _returnTModelVal1.setDeleted(Boolean.valueOf(false));
            _returnTModel.add(_returnTModelVal1);
            _return.getTModel().addAll(_returnTModel);
            _return.setTruncated(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#getBindingDetail(org.uddi.api_v3.GetBindingDetail  body )*
     */
    public org.uddi.api_v3.BindingDetail getBindingDetail(org.uddi.api_v3.GetBindingDetail body) { 
        LOG.info("Executing operation getBindingDetail");
        System.out.println(body);
        try {
            org.uddi.api_v3.BindingDetail _return = new org.uddi.api_v3.BindingDetail();
            org.uddi.api_v3.ListDescription _returnListDescription = new org.uddi.api_v3.ListDescription();
            _returnListDescription.setIncludeCount(-1728646498);
            _returnListDescription.setActualCount(-1181183784);
            _returnListDescription.setListHead(-1461661570);
            _return.setListDescription(_returnListDescription);
            java.util.List<org.uddi.api_v3.BindingTemplate> _returnBindingTemplate = new java.util.ArrayList<org.uddi.api_v3.BindingTemplate>();
            org.uddi.api_v3.BindingTemplate _returnBindingTemplateVal1 = new org.uddi.api_v3.BindingTemplate();
            java.util.List<org.uddi.api_v3.Description> _returnBindingTemplateVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
            _returnBindingTemplateVal1.getDescription().addAll(_returnBindingTemplateVal1Description);
            org.uddi.api_v3.AccessPoint _returnBindingTemplateVal1AccessPoint = new org.uddi.api_v3.AccessPoint();
            _returnBindingTemplateVal1AccessPoint.setValue("Value1563044262");
            _returnBindingTemplateVal1AccessPoint.setUseType("UseType304325585");
            _returnBindingTemplateVal1.setAccessPoint(_returnBindingTemplateVal1AccessPoint);
            org.uddi.api_v3.HostingRedirector _returnBindingTemplateVal1HostingRedirector = new org.uddi.api_v3.HostingRedirector();
            _returnBindingTemplateVal1HostingRedirector.setBindingKey("BindingKey1210680496");
            _returnBindingTemplateVal1.setHostingRedirector(_returnBindingTemplateVal1HostingRedirector);
            org.uddi.api_v3.TModelInstanceDetails _returnBindingTemplateVal1TModelInstanceDetails = new org.uddi.api_v3.TModelInstanceDetails();
            java.util.List<org.uddi.api_v3.TModelInstanceInfo> _returnBindingTemplateVal1TModelInstanceDetailsTModelInstanceInfo = new java.util.ArrayList<org.uddi.api_v3.TModelInstanceInfo>();
            _returnBindingTemplateVal1TModelInstanceDetails.getTModelInstanceInfo().addAll(_returnBindingTemplateVal1TModelInstanceDetailsTModelInstanceInfo);
            _returnBindingTemplateVal1.setTModelInstanceDetails(_returnBindingTemplateVal1TModelInstanceDetails);
            org.uddi.api_v3.CategoryBag _returnBindingTemplateVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnBindingTemplateVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnBindingTemplateVal1CategoryBag.getKeyedReference().addAll(_returnBindingTemplateVal1CategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnBindingTemplateVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnBindingTemplateVal1CategoryBag.getKeyedReferenceGroup().addAll(_returnBindingTemplateVal1CategoryBagKeyedReferenceGroup);
            _returnBindingTemplateVal1.setCategoryBag(_returnBindingTemplateVal1CategoryBag);
            java.util.List<org.w3._2000._09.xmldsig.SignatureType> _returnBindingTemplateVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
            _returnBindingTemplateVal1.getSignature().addAll(_returnBindingTemplateVal1Signature);
            _returnBindingTemplateVal1.setBindingKey("BindingKey2030561930");
            _returnBindingTemplateVal1.setServiceKey("ServiceKey1299126302");
            _returnBindingTemplate.add(_returnBindingTemplateVal1);
            _return.getBindingTemplate().addAll(_returnBindingTemplate);
            _return.setTruncated(Boolean.valueOf(false));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#findService(org.uddi.api_v3.FindService  body )*
     */
    public org.uddi.api_v3.ServiceList findService(org.uddi.api_v3.FindService body) { 
        LOG.info("Executing operation findService");
        System.out.println(body);
        try {
            org.uddi.api_v3.ServiceList _return = new org.uddi.api_v3.ServiceList();
            org.uddi.api_v3.ListDescription _returnListDescription = new org.uddi.api_v3.ListDescription();
            _returnListDescription.setIncludeCount(839570498);
            _returnListDescription.setActualCount(1323951618);
            _returnListDescription.setListHead(-1359151038);
            _return.setListDescription(_returnListDescription);
            org.uddi.api_v3.ServiceInfos _returnServiceInfos = new org.uddi.api_v3.ServiceInfos();
            java.util.List<org.uddi.api_v3.ServiceInfo> _returnServiceInfosServiceInfo = new java.util.ArrayList<org.uddi.api_v3.ServiceInfo>();
            org.uddi.api_v3.ServiceInfo _returnServiceInfosServiceInfoVal1 = new org.uddi.api_v3.ServiceInfo();
            java.util.List<org.uddi.api_v3.Name> _returnServiceInfosServiceInfoVal1Name = new java.util.ArrayList<org.uddi.api_v3.Name>();
            _returnServiceInfosServiceInfoVal1.getName().addAll(_returnServiceInfosServiceInfoVal1Name);
            _returnServiceInfosServiceInfoVal1.setServiceKey("ServiceKey-839759637");
            _returnServiceInfosServiceInfoVal1.setBusinessKey("BusinessKey679681388");
            _returnServiceInfosServiceInfo.add(_returnServiceInfosServiceInfoVal1);
            _returnServiceInfos.getServiceInfo().addAll(_returnServiceInfosServiceInfo);
            _return.setServiceInfos(_returnServiceInfos);
            _return.setTruncated(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#getServiceDetail(org.uddi.api_v3.GetServiceDetail  body )*
     */
    public org.uddi.api_v3.ServiceDetail getServiceDetail(org.uddi.api_v3.GetServiceDetail body) { 
        LOG.info("Executing operation getServiceDetail");
        System.out.println(body);
        try {
            org.uddi.api_v3.ServiceDetail _return = new org.uddi.api_v3.ServiceDetail();
            java.util.List<org.uddi.api_v3.BusinessService> _returnBusinessService = new java.util.ArrayList<org.uddi.api_v3.BusinessService>();
            org.uddi.api_v3.BusinessService _returnBusinessServiceVal1 = new org.uddi.api_v3.BusinessService();
            java.util.List<org.uddi.api_v3.Name> _returnBusinessServiceVal1Name = new java.util.ArrayList<org.uddi.api_v3.Name>();
            _returnBusinessServiceVal1.getName().addAll(_returnBusinessServiceVal1Name);
            java.util.List<org.uddi.api_v3.Description> _returnBusinessServiceVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
            _returnBusinessServiceVal1.getDescription().addAll(_returnBusinessServiceVal1Description);
            org.uddi.api_v3.BindingTemplates _returnBusinessServiceVal1BindingTemplates = new org.uddi.api_v3.BindingTemplates();
            java.util.List<org.uddi.api_v3.BindingTemplate> _returnBusinessServiceVal1BindingTemplatesBindingTemplate = new java.util.ArrayList<org.uddi.api_v3.BindingTemplate>();
            _returnBusinessServiceVal1BindingTemplates.getBindingTemplate().addAll(_returnBusinessServiceVal1BindingTemplatesBindingTemplate);
            _returnBusinessServiceVal1.setBindingTemplates(_returnBusinessServiceVal1BindingTemplates);
            org.uddi.api_v3.CategoryBag _returnBusinessServiceVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnBusinessServiceVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnBusinessServiceVal1CategoryBag.getKeyedReference().addAll(_returnBusinessServiceVal1CategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnBusinessServiceVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnBusinessServiceVal1CategoryBag.getKeyedReferenceGroup().addAll(_returnBusinessServiceVal1CategoryBagKeyedReferenceGroup);
            _returnBusinessServiceVal1.setCategoryBag(_returnBusinessServiceVal1CategoryBag);
            java.util.List<org.w3._2000._09.xmldsig.SignatureType> _returnBusinessServiceVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
            _returnBusinessServiceVal1.getSignature().addAll(_returnBusinessServiceVal1Signature);
            _returnBusinessServiceVal1.setServiceKey("ServiceKey1086244474");
            _returnBusinessServiceVal1.setBusinessKey("BusinessKey-496203092");
            _returnBusinessService.add(_returnBusinessServiceVal1);
            _return.getBusinessService().addAll(_returnBusinessService);
            _return.setTruncated(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#findBinding(org.uddi.api_v3.FindBinding  body )*
     */
    public org.uddi.api_v3.BindingDetail findBinding(org.uddi.api_v3.FindBinding body) { 
        LOG.info("Executing operation findBinding");
        System.out.println(body);
        try {
            org.uddi.api_v3.BindingDetail _return = new org.uddi.api_v3.BindingDetail();
            org.uddi.api_v3.ListDescription _returnListDescription = new org.uddi.api_v3.ListDescription();
            _returnListDescription.setIncludeCount(-1731638062);
            _returnListDescription.setActualCount(722711131);
            _returnListDescription.setListHead(-1640223645);
            _return.setListDescription(_returnListDescription);
            java.util.List<org.uddi.api_v3.BindingTemplate> _returnBindingTemplate = new java.util.ArrayList<org.uddi.api_v3.BindingTemplate>();
            org.uddi.api_v3.BindingTemplate _returnBindingTemplateVal1 = new org.uddi.api_v3.BindingTemplate();
            java.util.List<org.uddi.api_v3.Description> _returnBindingTemplateVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
            _returnBindingTemplateVal1.getDescription().addAll(_returnBindingTemplateVal1Description);
            org.uddi.api_v3.AccessPoint _returnBindingTemplateVal1AccessPoint = new org.uddi.api_v3.AccessPoint();
            _returnBindingTemplateVal1AccessPoint.setValue("Value2018643725");
            _returnBindingTemplateVal1AccessPoint.setUseType("UseType-408610946");
            _returnBindingTemplateVal1.setAccessPoint(_returnBindingTemplateVal1AccessPoint);
            org.uddi.api_v3.HostingRedirector _returnBindingTemplateVal1HostingRedirector = new org.uddi.api_v3.HostingRedirector();
            _returnBindingTemplateVal1HostingRedirector.setBindingKey("BindingKey920997638");
            _returnBindingTemplateVal1.setHostingRedirector(_returnBindingTemplateVal1HostingRedirector);
            org.uddi.api_v3.TModelInstanceDetails _returnBindingTemplateVal1TModelInstanceDetails = new org.uddi.api_v3.TModelInstanceDetails();
            java.util.List<org.uddi.api_v3.TModelInstanceInfo> _returnBindingTemplateVal1TModelInstanceDetailsTModelInstanceInfo = new java.util.ArrayList<org.uddi.api_v3.TModelInstanceInfo>();
            _returnBindingTemplateVal1TModelInstanceDetails.getTModelInstanceInfo().addAll(_returnBindingTemplateVal1TModelInstanceDetailsTModelInstanceInfo);
            _returnBindingTemplateVal1.setTModelInstanceDetails(_returnBindingTemplateVal1TModelInstanceDetails);
            org.uddi.api_v3.CategoryBag _returnBindingTemplateVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnBindingTemplateVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnBindingTemplateVal1CategoryBag.getKeyedReference().addAll(_returnBindingTemplateVal1CategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnBindingTemplateVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnBindingTemplateVal1CategoryBag.getKeyedReferenceGroup().addAll(_returnBindingTemplateVal1CategoryBagKeyedReferenceGroup);
            _returnBindingTemplateVal1.setCategoryBag(_returnBindingTemplateVal1CategoryBag);
            java.util.List<org.w3._2000._09.xmldsig.SignatureType> _returnBindingTemplateVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
            _returnBindingTemplateVal1.getSignature().addAll(_returnBindingTemplateVal1Signature);
            _returnBindingTemplateVal1.setBindingKey("BindingKey-1957586144");
            _returnBindingTemplateVal1.setServiceKey("ServiceKey-1810550558");
            _returnBindingTemplate.add(_returnBindingTemplateVal1);
            _return.getBindingTemplate().addAll(_returnBindingTemplate);
            _return.setTruncated(Boolean.valueOf(false));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#findTModel(org.uddi.api_v3.FindTModel  body )*
     */
    public org.uddi.api_v3.TModelList findTModel(org.uddi.api_v3.FindTModel body) { 
        LOG.info("Executing operation findTModel");
        System.out.println(body);
        try {
            org.uddi.api_v3.TModelList _return = new org.uddi.api_v3.TModelList();
            org.uddi.api_v3.ListDescription _returnListDescription = new org.uddi.api_v3.ListDescription();
            _returnListDescription.setIncludeCount(-1584370226);
            _returnListDescription.setActualCount(-476689192);
            _returnListDescription.setListHead(2075241805);
            _return.setListDescription(_returnListDescription);
            org.uddi.api_v3.TModelInfos _returnTModelInfos = new org.uddi.api_v3.TModelInfos();
            java.util.List<org.uddi.api_v3.TModelInfo> _returnTModelInfosTModelInfo = new java.util.ArrayList<org.uddi.api_v3.TModelInfo>();
            org.uddi.api_v3.TModelInfo _returnTModelInfosTModelInfoVal1 = new org.uddi.api_v3.TModelInfo();
            org.uddi.api_v3.Name _returnTModelInfosTModelInfoVal1Name = new org.uddi.api_v3.Name();
            _returnTModelInfosTModelInfoVal1Name.setValue("Value-633111255");
            _returnTModelInfosTModelInfoVal1Name.setLang("Lang1468608285");
            _returnTModelInfosTModelInfoVal1.setName(_returnTModelInfosTModelInfoVal1Name);
            java.util.List<org.uddi.api_v3.Description> _returnTModelInfosTModelInfoVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
            _returnTModelInfosTModelInfoVal1.getDescription().addAll(_returnTModelInfosTModelInfoVal1Description);
            _returnTModelInfosTModelInfoVal1.setTModelKey("TModelKey-755932807");
            _returnTModelInfosTModelInfo.add(_returnTModelInfosTModelInfoVal1);
            _returnTModelInfos.getTModelInfo().addAll(_returnTModelInfosTModelInfo);
            _return.setTModelInfos(_returnTModelInfos);
            _return.setTruncated(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#findRelatedBusinesses(org.uddi.api_v3.FindRelatedBusinesses  body )*
     */
    public org.uddi.api_v3.RelatedBusinessesList findRelatedBusinesses(org.uddi.api_v3.FindRelatedBusinesses body) { 
        LOG.info("Executing operation findRelatedBusinesses");
        System.out.println(body);
        try {
            org.uddi.api_v3.RelatedBusinessesList _return = new org.uddi.api_v3.RelatedBusinessesList();
            org.uddi.api_v3.ListDescription _returnListDescription = new org.uddi.api_v3.ListDescription();
            _returnListDescription.setIncludeCount(648376139);
            _returnListDescription.setActualCount(1002190231);
            _returnListDescription.setListHead(-1932738243);
            _return.setListDescription(_returnListDescription);
            _return.setBusinessKey("BusinessKey-914481242");
            org.uddi.api_v3.RelatedBusinessInfos _returnRelatedBusinessInfos = new org.uddi.api_v3.RelatedBusinessInfos();
            java.util.List<org.uddi.api_v3.RelatedBusinessInfo> _returnRelatedBusinessInfosRelatedBusinessInfo = new java.util.ArrayList<org.uddi.api_v3.RelatedBusinessInfo>();
            org.uddi.api_v3.RelatedBusinessInfo _returnRelatedBusinessInfosRelatedBusinessInfoVal1 = new org.uddi.api_v3.RelatedBusinessInfo();
            _returnRelatedBusinessInfosRelatedBusinessInfoVal1.setBusinessKey("BusinessKey2125567073");
            java.util.List<org.uddi.api_v3.Name> _returnRelatedBusinessInfosRelatedBusinessInfoVal1Name = new java.util.ArrayList<org.uddi.api_v3.Name>();
            _returnRelatedBusinessInfosRelatedBusinessInfoVal1.getName().addAll(_returnRelatedBusinessInfosRelatedBusinessInfoVal1Name);
            java.util.List<org.uddi.api_v3.Description> _returnRelatedBusinessInfosRelatedBusinessInfoVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
            _returnRelatedBusinessInfosRelatedBusinessInfoVal1.getDescription().addAll(_returnRelatedBusinessInfosRelatedBusinessInfoVal1Description);
            java.util.List<org.uddi.api_v3.SharedRelationships> _returnRelatedBusinessInfosRelatedBusinessInfoVal1SharedRelationships = new java.util.ArrayList<org.uddi.api_v3.SharedRelationships>();
            _returnRelatedBusinessInfosRelatedBusinessInfoVal1.getSharedRelationships().addAll(_returnRelatedBusinessInfosRelatedBusinessInfoVal1SharedRelationships);
            _returnRelatedBusinessInfosRelatedBusinessInfo.add(_returnRelatedBusinessInfosRelatedBusinessInfoVal1);
            _returnRelatedBusinessInfos.getRelatedBusinessInfo().addAll(_returnRelatedBusinessInfosRelatedBusinessInfo);
            _return.setRelatedBusinessInfos(_returnRelatedBusinessInfos);
            _return.setTruncated(Boolean.valueOf(false));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#getBusinessDetail(org.uddi.api_v3.GetBusinessDetail  body )*
     */
    public org.uddi.api_v3.BusinessDetail getBusinessDetail(org.uddi.api_v3.GetBusinessDetail body) { 
        LOG.info("Executing operation getBusinessDetail");
        System.out.println(body);
        try {
            org.uddi.api_v3.BusinessDetail _return = new org.uddi.api_v3.BusinessDetail();
            java.util.List<org.uddi.api_v3.BusinessEntity> _returnBusinessEntity = new java.util.ArrayList<org.uddi.api_v3.BusinessEntity>();
            org.uddi.api_v3.BusinessEntity _returnBusinessEntityVal1 = new org.uddi.api_v3.BusinessEntity();
            org.uddi.api_v3.DiscoveryURLs _returnBusinessEntityVal1DiscoveryURLs = new org.uddi.api_v3.DiscoveryURLs();
            java.util.List<org.uddi.api_v3.DiscoveryURL> _returnBusinessEntityVal1DiscoveryURLsDiscoveryURL = new java.util.ArrayList<org.uddi.api_v3.DiscoveryURL>();
            _returnBusinessEntityVal1DiscoveryURLs.getDiscoveryURL().addAll(_returnBusinessEntityVal1DiscoveryURLsDiscoveryURL);
            _returnBusinessEntityVal1.setDiscoveryURLs(_returnBusinessEntityVal1DiscoveryURLs);
            java.util.List<org.uddi.api_v3.Name> _returnBusinessEntityVal1Name = new java.util.ArrayList<org.uddi.api_v3.Name>();
            _returnBusinessEntityVal1.getName().addAll(_returnBusinessEntityVal1Name);
            java.util.List<org.uddi.api_v3.Description> _returnBusinessEntityVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
            _returnBusinessEntityVal1.getDescription().addAll(_returnBusinessEntityVal1Description);
            org.uddi.api_v3.Contacts _returnBusinessEntityVal1Contacts = new org.uddi.api_v3.Contacts();
            java.util.List<org.uddi.api_v3.Contact> _returnBusinessEntityVal1ContactsContact = new java.util.ArrayList<org.uddi.api_v3.Contact>();
            _returnBusinessEntityVal1Contacts.getContact().addAll(_returnBusinessEntityVal1ContactsContact);
            _returnBusinessEntityVal1.setContacts(_returnBusinessEntityVal1Contacts);
            org.uddi.api_v3.BusinessServices _returnBusinessEntityVal1BusinessServices = new org.uddi.api_v3.BusinessServices();
            java.util.List<org.uddi.api_v3.BusinessService> _returnBusinessEntityVal1BusinessServicesBusinessService = new java.util.ArrayList<org.uddi.api_v3.BusinessService>();
            _returnBusinessEntityVal1BusinessServices.getBusinessService().addAll(_returnBusinessEntityVal1BusinessServicesBusinessService);
            _returnBusinessEntityVal1.setBusinessServices(_returnBusinessEntityVal1BusinessServices);
            org.uddi.api_v3.IdentifierBag _returnBusinessEntityVal1IdentifierBag = new org.uddi.api_v3.IdentifierBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnBusinessEntityVal1IdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnBusinessEntityVal1IdentifierBag.getKeyedReference().addAll(_returnBusinessEntityVal1IdentifierBagKeyedReference);
            _returnBusinessEntityVal1.setIdentifierBag(_returnBusinessEntityVal1IdentifierBag);
            org.uddi.api_v3.CategoryBag _returnBusinessEntityVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnBusinessEntityVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnBusinessEntityVal1CategoryBag.getKeyedReference().addAll(_returnBusinessEntityVal1CategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnBusinessEntityVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnBusinessEntityVal1CategoryBag.getKeyedReferenceGroup().addAll(_returnBusinessEntityVal1CategoryBagKeyedReferenceGroup);
            _returnBusinessEntityVal1.setCategoryBag(_returnBusinessEntityVal1CategoryBag);
            java.util.List<org.w3._2000._09.xmldsig.SignatureType> _returnBusinessEntityVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
            _returnBusinessEntityVal1.getSignature().addAll(_returnBusinessEntityVal1Signature);
            _returnBusinessEntityVal1.setBusinessKey("BusinessKey1654475842");
            _returnBusinessEntity.add(_returnBusinessEntityVal1);
            _return.getBusinessEntity().addAll(_returnBusinessEntity);
            _return.setTruncated(Boolean.valueOf(false));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#findBusiness(org.uddi.api_v3.FindBusiness  body )*
     */
    public org.uddi.api_v3.BusinessList findBusiness(org.uddi.api_v3.FindBusiness body) { 
        LOG.info("Executing operation findBusiness");
        System.out.println(body);
        try {
            org.uddi.api_v3.BusinessList _return = new org.uddi.api_v3.BusinessList();
            org.uddi.api_v3.ListDescription _returnListDescription = new org.uddi.api_v3.ListDescription();
            _returnListDescription.setIncludeCount(2128639467);
            _returnListDescription.setActualCount(-378084774);
            _returnListDescription.setListHead(-972689574);
            _return.setListDescription(_returnListDescription);
            org.uddi.api_v3.BusinessInfos _returnBusinessInfos = new org.uddi.api_v3.BusinessInfos();
            java.util.List<org.uddi.api_v3.BusinessInfo> _returnBusinessInfosBusinessInfo = new java.util.ArrayList<org.uddi.api_v3.BusinessInfo>();
            org.uddi.api_v3.BusinessInfo _returnBusinessInfosBusinessInfoVal1 = new org.uddi.api_v3.BusinessInfo();
            java.util.List<org.uddi.api_v3.Name> _returnBusinessInfosBusinessInfoVal1Name = new java.util.ArrayList<org.uddi.api_v3.Name>();
            _returnBusinessInfosBusinessInfoVal1.getName().addAll(_returnBusinessInfosBusinessInfoVal1Name);
            java.util.List<org.uddi.api_v3.Description> _returnBusinessInfosBusinessInfoVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
            _returnBusinessInfosBusinessInfoVal1.getDescription().addAll(_returnBusinessInfosBusinessInfoVal1Description);
            org.uddi.api_v3.ServiceInfos _returnBusinessInfosBusinessInfoVal1ServiceInfos = new org.uddi.api_v3.ServiceInfos();
            java.util.List<org.uddi.api_v3.ServiceInfo> _returnBusinessInfosBusinessInfoVal1ServiceInfosServiceInfo = new java.util.ArrayList<org.uddi.api_v3.ServiceInfo>();
            _returnBusinessInfosBusinessInfoVal1ServiceInfos.getServiceInfo().addAll(_returnBusinessInfosBusinessInfoVal1ServiceInfosServiceInfo);
            _returnBusinessInfosBusinessInfoVal1.setServiceInfos(_returnBusinessInfosBusinessInfoVal1ServiceInfos);
            _returnBusinessInfosBusinessInfoVal1.setBusinessKey("BusinessKey-1102473769");
            _returnBusinessInfosBusinessInfo.add(_returnBusinessInfosBusinessInfoVal1);
            _returnBusinessInfos.getBusinessInfo().addAll(_returnBusinessInfosBusinessInfo);
            _return.setBusinessInfos(_returnBusinessInfos);
            _return.setTruncated(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDIInquiryPortType#getOperationalInfo(org.uddi.api_v3.GetOperationalInfo  body )*
     */
    public org.uddi.api_v3.OperationalInfos getOperationalInfo(org.uddi.api_v3.GetOperationalInfo body) { 
        LOG.info("Executing operation getOperationalInfo");
        System.out.println(body);
        try {
            org.uddi.api_v3.OperationalInfos _return = new org.uddi.api_v3.OperationalInfos();
            java.util.List<org.uddi.api_v3.OperationalInfo> _returnOperationalInfo = new java.util.ArrayList<org.uddi.api_v3.OperationalInfo>();
            org.uddi.api_v3.OperationalInfo _returnOperationalInfoVal1 = new org.uddi.api_v3.OperationalInfo();
            java.lang.Object _returnOperationalInfoVal1Created = null;
            _returnOperationalInfoVal1.setCreated(_returnOperationalInfoVal1Created);
            java.lang.Object _returnOperationalInfoVal1Modified = null;
            _returnOperationalInfoVal1.setModified(_returnOperationalInfoVal1Modified);
            java.lang.Object _returnOperationalInfoVal1ModifiedIncludingChildren = null;
            _returnOperationalInfoVal1.setModifiedIncludingChildren(_returnOperationalInfoVal1ModifiedIncludingChildren);
            _returnOperationalInfoVal1.setNodeID("NodeID-1613691695");
            _returnOperationalInfoVal1.setAuthorizedName("AuthorizedName-1839812064");
            _returnOperationalInfoVal1.setEntityKey("EntityKey306915798");
            _returnOperationalInfo.add(_returnOperationalInfoVal1);
            _return.getOperationalInfo().addAll(_returnOperationalInfo);
            _return.setTruncated(Boolean.valueOf(false));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
