package org.uddi.v3_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-07T19:55:12.095+01:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebService(targetNamespace = "urn:uddi-org:v3_service", name = "UDDI_Inquiry_PortType")
@XmlSeeAlso({org.uddi.custody_v3.ObjectFactory.class, org.uddi.api_v3.ObjectFactory.class, org.uddi.repl_v3.ObjectFactory.class, org.uddi.sub_v3.ObjectFactory.class, org.uddi.vs_v3.ObjectFactory.class, org.uddi.policy_v3.ObjectFactory.class, org.uddi.vscache_v3.ObjectFactory.class, org.uddi.policy_v3_instanceparms.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, org.uddi.subr_v3.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UDDIInquiryPortType {

    @WebResult(name = "tModelDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_tModelDetail", action = "get_tModelDetail")
    public org.uddi.api_v3.TModelDetail getTModelDetail(
        @WebParam(partName = "body", name = "get_tModelDetail", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetTModelDetail body
    );

    @WebResult(name = "bindingDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_bindingDetail", action = "get_bindingDetail")
    public org.uddi.api_v3.BindingDetail getBindingDetail(
        @WebParam(partName = "body", name = "get_bindingDetail", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetBindingDetail body
    );

    @WebResult(name = "serviceList", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_service", action = "find_service")
    public org.uddi.api_v3.ServiceList findService(
        @WebParam(partName = "body", name = "find_service", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindService body
    );

    @WebResult(name = "serviceDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_serviceDetail", action = "get_serviceDetail")
    public org.uddi.api_v3.ServiceDetail getServiceDetail(
        @WebParam(partName = "body", name = "get_serviceDetail", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetServiceDetail body
    );

    @WebResult(name = "bindingDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_binding", action = "find_binding")
    public org.uddi.api_v3.BindingDetail findBinding(
        @WebParam(partName = "body", name = "find_binding", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindBinding body
    );

    @WebResult(name = "tModelList", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_tModel", action = "find_tModel")
    public org.uddi.api_v3.TModelList findTModel(
        @WebParam(partName = "body", name = "find_tModel", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindTModel body
    );

    @WebResult(name = "relatedBusinessesList", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_relatedBusinesses", action = "find_relatedBusinesses")
    public org.uddi.api_v3.RelatedBusinessesList findRelatedBusinesses(
        @WebParam(partName = "body", name = "find_relatedBusinesses", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindRelatedBusinesses body
    );

    @WebResult(name = "businessDetail", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_businessDetail", action = "get_businessDetail")
    public org.uddi.api_v3.BusinessDetail getBusinessDetail(
        @WebParam(partName = "body", name = "get_businessDetail", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetBusinessDetail body
    );

    @WebResult(name = "businessList", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "find_business", action = "find_business")
    public org.uddi.api_v3.BusinessList findBusiness(
        @WebParam(partName = "body", name = "find_business", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.FindBusiness body
    );

    @WebResult(name = "operationalInfos", targetNamespace = "urn:uddi-org:api_v3", partName = "body")
    @WebMethod(operationName = "get_operationalInfo", action = "get_operationalInfo")
    public org.uddi.api_v3.OperationalInfos getOperationalInfo(
        @WebParam(partName = "body", name = "get_operationalInfo", targetNamespace = "urn:uddi-org:api_v3")
        org.uddi.api_v3.GetOperationalInfo body
    );
}
