//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desguaceNET.desguaceWS_Silvia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gestor_desguace_java/", ConfigurationName="desguaceWS_Silvia.DesguaceJavaWS")]
    public interface DesguaceJavaWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/getOfertasRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/getOfertasResponse")]
        desguaceNET.desguaceWS_Silvia.getOfertasResponse getOfertas(desguaceNET.desguaceWS_Silvia.getOfertasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/getOfertasRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/getOfertasResponse")]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.getOfertasResponse> getOfertasAsync(desguaceNET.desguaceWS_Silvia.getOfertasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento oferta del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/nuevaOfertaRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/nuevaOfertaResponse")]
        desguaceNET.desguaceWS_Silvia.nuevaOfertaResponse nuevaOferta(desguaceNET.desguaceWS_Silvia.nuevaOfertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/nuevaOfertaRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/nuevaOfertaResponse")]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.nuevaOfertaResponse> nuevaOfertaAsync(desguaceNET.desguaceWS_Silvia.nuevaOfertaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mail del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/checkActivacionRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/checkActivacionResponse")]
        desguaceNET.desguaceWS_Silvia.checkActivacionResponse checkActivacion(desguaceNET.desguaceWS_Silvia.checkActivacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/checkActivacionRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/checkActivacionResponse")]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.checkActivacionResponse> checkActivacionAsync(desguaceNET.desguaceWS_Silvia.checkActivacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento string del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/getPedidosporIDRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/getPedidosporIDResponse")]
        desguaceNET.desguaceWS_Silvia.getPedidosporIDResponse getPedidosporID(desguaceNET.desguaceWS_Silvia.getPedidosporIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/getPedidosporIDRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/getPedidosporIDResponse")]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.getPedidosporIDResponse> getPedidosporIDAsync(desguaceNET.desguaceWS_Silvia.getPedidosporIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/aceptarOfertaFinRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/aceptarOfertaFinResponse")]
        desguaceNET.desguaceWS_Silvia.aceptarOfertaFinResponse aceptarOfertaFin(desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/aceptarOfertaFinRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/aceptarOfertaFinResponse")]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.aceptarOfertaFinResponse> aceptarOfertaFinAsync(desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/cancelarOfertaRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/cancelarOfertaResponse")]
        desguaceNET.desguaceWS_Silvia.cancelarOfertaResponse cancelarOferta(desguaceNET.desguaceWS_Silvia.cancelarOfertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/cancelarOfertaRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/cancelarOfertaResponse")]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.cancelarOfertaResponse> cancelarOfertaAsync(desguaceNET.desguaceWS_Silvia.cancelarOfertaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/altaRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/altaResponse")]
        desguaceNET.desguaceWS_Silvia.altaResponse alta(desguaceNET.desguaceWS_Silvia.altaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gestor_desguace_java/DesguaceJavaWS/altaRequest", ReplyAction="http://gestor_desguace_java/DesguaceJavaWS/altaResponse")]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.altaResponse> altaAsync(desguaceNET.desguaceWS_Silvia.altaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOfertasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOfertas", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.getOfertasRequestBody Body;
        
        public getOfertasRequest() {
        }
        
        public getOfertasRequest(desguaceNET.desguaceWS_Silvia.getOfertasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getOfertasRequestBody {
        
        public getOfertasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOfertasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOfertasResponse", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.getOfertasResponseBody Body;
        
        public getOfertasResponse() {
        }
        
        public getOfertasResponse(desguaceNET.desguaceWS_Silvia.getOfertasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getOfertasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getOfertasResponseBody() {
        }
        
        public getOfertasResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nuevaOfertaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nuevaOferta", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.nuevaOfertaRequestBody Body;
        
        public nuevaOfertaRequest() {
        }
        
        public nuevaOfertaRequest(desguaceNET.desguaceWS_Silvia.nuevaOfertaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class nuevaOfertaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string oferta;
        
        public nuevaOfertaRequestBody() {
        }
        
        public nuevaOfertaRequestBody(string oferta) {
            this.oferta = oferta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nuevaOfertaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nuevaOfertaResponse", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.nuevaOfertaResponseBody Body;
        
        public nuevaOfertaResponse() {
        }
        
        public nuevaOfertaResponse(desguaceNET.desguaceWS_Silvia.nuevaOfertaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class nuevaOfertaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public nuevaOfertaResponseBody() {
        }
        
        public nuevaOfertaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkActivacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkActivacion", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.checkActivacionRequestBody Body;
        
        public checkActivacionRequest() {
        }
        
        public checkActivacionRequest(desguaceNET.desguaceWS_Silvia.checkActivacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkActivacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mail;
        
        public checkActivacionRequestBody() {
        }
        
        public checkActivacionRequestBody(string mail) {
            this.mail = mail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkActivacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkActivacionResponse", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.checkActivacionResponseBody Body;
        
        public checkActivacionResponse() {
        }
        
        public checkActivacionResponse(desguaceNET.desguaceWS_Silvia.checkActivacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkActivacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public checkActivacionResponseBody() {
        }
        
        public checkActivacionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPedidosporIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPedidosporID", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.getPedidosporIDRequestBody Body;
        
        public getPedidosporIDRequest() {
        }
        
        public getPedidosporIDRequest(desguaceNET.desguaceWS_Silvia.getPedidosporIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getPedidosporIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @string;
        
        public getPedidosporIDRequestBody() {
        }
        
        public getPedidosporIDRequestBody(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPedidosporIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPedidosporIDResponse", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.getPedidosporIDResponseBody Body;
        
        public getPedidosporIDResponse() {
        }
        
        public getPedidosporIDResponse(desguaceNET.desguaceWS_Silvia.getPedidosporIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getPedidosporIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getPedidosporIDResponseBody() {
        }
        
        public getPedidosporIDResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aceptarOfertaFinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aceptarOfertaFin", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequestBody Body;
        
        public aceptarOfertaFinRequest() {
        }
        
        public aceptarOfertaFinRequest(desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aceptarOfertaFinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public aceptarOfertaFinRequestBody() {
        }
        
        public aceptarOfertaFinRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aceptarOfertaFinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aceptarOfertaFinResponse", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.aceptarOfertaFinResponseBody Body;
        
        public aceptarOfertaFinResponse() {
        }
        
        public aceptarOfertaFinResponse(desguaceNET.desguaceWS_Silvia.aceptarOfertaFinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aceptarOfertaFinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public aceptarOfertaFinResponseBody() {
        }
        
        public aceptarOfertaFinResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarOfertaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelarOferta", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.cancelarOfertaRequestBody Body;
        
        public cancelarOfertaRequest() {
        }
        
        public cancelarOfertaRequest(desguaceNET.desguaceWS_Silvia.cancelarOfertaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cancelarOfertaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public cancelarOfertaRequestBody() {
        }
        
        public cancelarOfertaRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarOfertaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelarOfertaResponse", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.cancelarOfertaResponseBody Body;
        
        public cancelarOfertaResponse() {
        }
        
        public cancelarOfertaResponse(desguaceNET.desguaceWS_Silvia.cancelarOfertaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class cancelarOfertaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public cancelarOfertaResponseBody() {
        }
        
        public cancelarOfertaResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class altaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="alta", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.altaRequestBody Body;
        
        public altaRequest() {
        }
        
        public altaRequest(desguaceNET.desguaceWS_Silvia.altaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class altaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int postalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int telephone;
        
        public altaRequestBody() {
        }
        
        public altaRequestBody(string name, string email, string address, string city, int postalCode, int telephone) {
            this.name = name;
            this.email = email;
            this.address = address;
            this.city = city;
            this.postalCode = postalCode;
            this.telephone = telephone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class altaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="altaResponse", Namespace="http://gestor_desguace_java/", Order=0)]
        public desguaceNET.desguaceWS_Silvia.altaResponseBody Body;
        
        public altaResponse() {
        }
        
        public altaResponse(desguaceNET.desguaceWS_Silvia.altaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class altaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public altaResponseBody() {
        }
        
        public altaResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DesguaceJavaWSChannel : desguaceNET.desguaceWS_Silvia.DesguaceJavaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DesguaceJavaWSClient : System.ServiceModel.ClientBase<desguaceNET.desguaceWS_Silvia.DesguaceJavaWS>, desguaceNET.desguaceWS_Silvia.DesguaceJavaWS {
        
        public DesguaceJavaWSClient() {
        }
        
        public DesguaceJavaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DesguaceJavaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesguaceJavaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesguaceJavaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        desguaceNET.desguaceWS_Silvia.getOfertasResponse desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.getOfertas(desguaceNET.desguaceWS_Silvia.getOfertasRequest request) {
            return base.Channel.getOfertas(request);
        }
        
        public string getOfertas() {
            desguaceNET.desguaceWS_Silvia.getOfertasRequest inValue = new desguaceNET.desguaceWS_Silvia.getOfertasRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.getOfertasRequestBody();
            desguaceNET.desguaceWS_Silvia.getOfertasResponse retVal = ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).getOfertas(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.getOfertasResponse> desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.getOfertasAsync(desguaceNET.desguaceWS_Silvia.getOfertasRequest request) {
            return base.Channel.getOfertasAsync(request);
        }
        
        public System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.getOfertasResponse> getOfertasAsync() {
            desguaceNET.desguaceWS_Silvia.getOfertasRequest inValue = new desguaceNET.desguaceWS_Silvia.getOfertasRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.getOfertasRequestBody();
            return ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).getOfertasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        desguaceNET.desguaceWS_Silvia.nuevaOfertaResponse desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.nuevaOferta(desguaceNET.desguaceWS_Silvia.nuevaOfertaRequest request) {
            return base.Channel.nuevaOferta(request);
        }
        
        public string nuevaOferta(string oferta) {
            desguaceNET.desguaceWS_Silvia.nuevaOfertaRequest inValue = new desguaceNET.desguaceWS_Silvia.nuevaOfertaRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.nuevaOfertaRequestBody();
            inValue.Body.oferta = oferta;
            desguaceNET.desguaceWS_Silvia.nuevaOfertaResponse retVal = ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).nuevaOferta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.nuevaOfertaResponse> desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.nuevaOfertaAsync(desguaceNET.desguaceWS_Silvia.nuevaOfertaRequest request) {
            return base.Channel.nuevaOfertaAsync(request);
        }
        
        public System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.nuevaOfertaResponse> nuevaOfertaAsync(string oferta) {
            desguaceNET.desguaceWS_Silvia.nuevaOfertaRequest inValue = new desguaceNET.desguaceWS_Silvia.nuevaOfertaRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.nuevaOfertaRequestBody();
            inValue.Body.oferta = oferta;
            return ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).nuevaOfertaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        desguaceNET.desguaceWS_Silvia.checkActivacionResponse desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.checkActivacion(desguaceNET.desguaceWS_Silvia.checkActivacionRequest request) {
            return base.Channel.checkActivacion(request);
        }
        
        public string checkActivacion(string mail) {
            desguaceNET.desguaceWS_Silvia.checkActivacionRequest inValue = new desguaceNET.desguaceWS_Silvia.checkActivacionRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.checkActivacionRequestBody();
            inValue.Body.mail = mail;
            desguaceNET.desguaceWS_Silvia.checkActivacionResponse retVal = ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).checkActivacion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.checkActivacionResponse> desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.checkActivacionAsync(desguaceNET.desguaceWS_Silvia.checkActivacionRequest request) {
            return base.Channel.checkActivacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.checkActivacionResponse> checkActivacionAsync(string mail) {
            desguaceNET.desguaceWS_Silvia.checkActivacionRequest inValue = new desguaceNET.desguaceWS_Silvia.checkActivacionRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.checkActivacionRequestBody();
            inValue.Body.mail = mail;
            return ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).checkActivacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        desguaceNET.desguaceWS_Silvia.getPedidosporIDResponse desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.getPedidosporID(desguaceNET.desguaceWS_Silvia.getPedidosporIDRequest request) {
            return base.Channel.getPedidosporID(request);
        }
        
        public string getPedidosporID(string @string) {
            desguaceNET.desguaceWS_Silvia.getPedidosporIDRequest inValue = new desguaceNET.desguaceWS_Silvia.getPedidosporIDRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.getPedidosporIDRequestBody();
            inValue.Body.@string = @string;
            desguaceNET.desguaceWS_Silvia.getPedidosporIDResponse retVal = ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).getPedidosporID(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.getPedidosporIDResponse> desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.getPedidosporIDAsync(desguaceNET.desguaceWS_Silvia.getPedidosporIDRequest request) {
            return base.Channel.getPedidosporIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.getPedidosporIDResponse> getPedidosporIDAsync(string @string) {
            desguaceNET.desguaceWS_Silvia.getPedidosporIDRequest inValue = new desguaceNET.desguaceWS_Silvia.getPedidosporIDRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.getPedidosporIDRequestBody();
            inValue.Body.@string = @string;
            return ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).getPedidosporIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        desguaceNET.desguaceWS_Silvia.aceptarOfertaFinResponse desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.aceptarOfertaFin(desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequest request) {
            return base.Channel.aceptarOfertaFin(request);
        }
        
        public bool aceptarOfertaFin(string id) {
            desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequest inValue = new desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequestBody();
            inValue.Body.id = id;
            desguaceNET.desguaceWS_Silvia.aceptarOfertaFinResponse retVal = ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).aceptarOfertaFin(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.aceptarOfertaFinResponse> desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.aceptarOfertaFinAsync(desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequest request) {
            return base.Channel.aceptarOfertaFinAsync(request);
        }
        
        public System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.aceptarOfertaFinResponse> aceptarOfertaFinAsync(string id) {
            desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequest inValue = new desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.aceptarOfertaFinRequestBody();
            inValue.Body.id = id;
            return ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).aceptarOfertaFinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        desguaceNET.desguaceWS_Silvia.cancelarOfertaResponse desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.cancelarOferta(desguaceNET.desguaceWS_Silvia.cancelarOfertaRequest request) {
            return base.Channel.cancelarOferta(request);
        }
        
        public bool cancelarOferta(string id) {
            desguaceNET.desguaceWS_Silvia.cancelarOfertaRequest inValue = new desguaceNET.desguaceWS_Silvia.cancelarOfertaRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.cancelarOfertaRequestBody();
            inValue.Body.id = id;
            desguaceNET.desguaceWS_Silvia.cancelarOfertaResponse retVal = ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).cancelarOferta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.cancelarOfertaResponse> desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.cancelarOfertaAsync(desguaceNET.desguaceWS_Silvia.cancelarOfertaRequest request) {
            return base.Channel.cancelarOfertaAsync(request);
        }
        
        public System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.cancelarOfertaResponse> cancelarOfertaAsync(string id) {
            desguaceNET.desguaceWS_Silvia.cancelarOfertaRequest inValue = new desguaceNET.desguaceWS_Silvia.cancelarOfertaRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.cancelarOfertaRequestBody();
            inValue.Body.id = id;
            return ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).cancelarOfertaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        desguaceNET.desguaceWS_Silvia.altaResponse desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.alta(desguaceNET.desguaceWS_Silvia.altaRequest request) {
            return base.Channel.alta(request);
        }
        
        public bool alta(string name, string email, string address, string city, int postalCode, int telephone) {
            desguaceNET.desguaceWS_Silvia.altaRequest inValue = new desguaceNET.desguaceWS_Silvia.altaRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.altaRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.postalCode = postalCode;
            inValue.Body.telephone = telephone;
            desguaceNET.desguaceWS_Silvia.altaResponse retVal = ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).alta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.altaResponse> desguaceNET.desguaceWS_Silvia.DesguaceJavaWS.altaAsync(desguaceNET.desguaceWS_Silvia.altaRequest request) {
            return base.Channel.altaAsync(request);
        }
        
        public System.Threading.Tasks.Task<desguaceNET.desguaceWS_Silvia.altaResponse> altaAsync(string name, string email, string address, string city, int postalCode, int telephone) {
            desguaceNET.desguaceWS_Silvia.altaRequest inValue = new desguaceNET.desguaceWS_Silvia.altaRequest();
            inValue.Body = new desguaceNET.desguaceWS_Silvia.altaRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.postalCode = postalCode;
            inValue.Body.telephone = telephone;
            return ((desguaceNET.desguaceWS_Silvia.DesguaceJavaWS)(this)).altaAsync(inValue);
        }
    }
}
