
package gestor_admin.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * Fri Apr 11 12:43:52 CEST 2014
 * Generated source version: 3.0.0-milestone1
 */

@XmlRootElement(name = "addAccesoDesguace", namespace = "http://gestor_admin/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addAccesoDesguace", namespace = "http://gestor_admin/")

public class AddAccesoDesguace {

    @XmlElement(name = "ID")
    private java.lang.String ID;

    public java.lang.String getID() {
        return this.ID;
    }

    public void setID(java.lang.String newID)  {
        this.ID = newID;
    }

}

