
package gestor_admin.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * Sun Feb 16 19:36:32 CET 2014
 * Generated source version: 3.0.0-milestone1
 */

@XmlRootElement(name = "getOfertas", namespace = "http://gestor_admin/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOfertas", namespace = "http://gestor_admin/")

public class GetOfertas {


}

