
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gestor_desguace_java;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-16T18:50:15.634+01:00
 * Generated source version: 3.0.0-milestone1
 * 
 */

@javax.jws.WebService(
                      serviceName = "DesguaceJavaWS",
                      portName = "DesguaceJavaWSPort",
                      targetNamespace = "http://gestor_desguace_java/",
                      wsdlLocation = "http://localhost:8080/Gestor/services/DesguaceJavaWSPort?wsdl",
                      endpointInterface = "gestor_desguace_java.DesguaceJavaWS")
                      
public class DesguaceJavaWSImpl implements DesguaceJavaWS {

    private static final Logger LOG = Logger.getLogger(DesguaceJavaWSImpl.class.getName());

    /* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#alta(java.lang.String  name ,)java.lang.String  email ,)java.lang.String  address ,)java.lang.String  city ,)java.lang.String  postalCode ,)java.lang.String  telephone )*
     */
    public boolean alta(java.lang.String name,java.lang.String email,java.lang.String address,java.lang.String city,java.lang.String postalCode,java.lang.String telephone) { 
        LOG.info("Executing operation alta");
        System.out.println(name);
        System.out.println(email);
        System.out.println(address);
        System.out.println(city);
        System.out.println(postalCode);
        System.out.println(telephone);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#checkActivacion(java.lang.String  mail )*
     */
    public java.lang.String checkActivacion(java.lang.String mail) { 
        LOG.info("Executing operation checkActivacion");
        System.out.println(mail);
        try {
            java.lang.String _return = "_return454939150";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#getPedidosporID(java.lang.String  string )*
     */
    public java.lang.String getPedidosporID(java.lang.String string) { 
        LOG.info("Executing operation getPedidosporID");
        System.out.println(string);
        try {
            java.lang.String _return = "_return1171450980";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#aceptarOfertaFin(java.lang.String  id )*
     */
    public java.lang.Boolean aceptarOfertaFin(java.lang.String id) { 
        LOG.info("Executing operation aceptarOfertaFin");
        System.out.println(id);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#cambiarEstadoPedido(java.lang.String  id ,)java.lang.String  estado )*
     */
    public java.lang.Boolean cambiarEstadoPedido(java.lang.String id,java.lang.String estado) { 
        LOG.info("Executing operation cambiarEstadoPedido");
        System.out.println(id);
        System.out.println(estado);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#getOfertas(*
     */
    public java.lang.String getOfertas() { 
        LOG.info("Executing operation getOfertas");
        try {
            java.lang.String _return = "_return-2050146335";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#baja(java.lang.String  id )*
     */
    public java.lang.Boolean baja(java.lang.String id) { 
        LOG.info("Executing operation baja");
        System.out.println(id);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#nuevaOferta(java.lang.String  oferta )*
     */
    public java.lang.String nuevaOferta(java.lang.String oferta) { 
        LOG.info("Executing operation nuevaOferta");
        System.out.println(oferta);
        try {
            java.lang.String _return = "_return266517288";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public java.lang.Boolean cambiarEstadoPedidoOtravez(java.lang.String id,java.lang.String estado) { 
        LOG.info("Executing operation cambiarEstadoPedidoOtravez");
        System.out.println(id);
        System.out.println(estado);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	/* (non-Javadoc)
     * @see gestor_desguace_java.DesguaceJavaWS#cancelarOferta(java.lang.String  id )*
     */
    public java.lang.Boolean cancelarOferta(java.lang.String id) { 
        LOG.info("Executing operation cancelarOferta");
        System.out.println(id);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
