package gestor_desguace_java;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-09T21:42:47.858+01:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebServiceClient(name = "DesguaceJavaWS", 
                  wsdlLocation = "file:/C:/Users/Silvia/workspace/SOR/Gestor/WebContent/wsdl/desguacejavaws.wsdl",
                  targetNamespace = "http://gestor_desguace_java/") 
public class DesguaceJavaWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gestor_desguace_java/", "DesguaceJavaWS");
    public final static QName DesguaceJavaWSPort = new QName("http://gestor_desguace_java/", "DesguaceJavaWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Silvia/workspace/SOR/Gestor/WebContent/wsdl/desguacejavaws.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DesguaceJavaWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Silvia/workspace/SOR/Gestor/WebContent/wsdl/desguacejavaws.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DesguaceJavaWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DesguaceJavaWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DesguaceJavaWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DesguaceJavaWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DesguaceJavaWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DesguaceJavaWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns DesguaceJavaWS
     */
    @WebEndpoint(name = "DesguaceJavaWSPort")
    public DesguaceJavaWS getDesguaceJavaWSPort() {
        return super.getPort(DesguaceJavaWSPort, DesguaceJavaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DesguaceJavaWS
     */
    @WebEndpoint(name = "DesguaceJavaWSPort")
    public DesguaceJavaWS getDesguaceJavaWSPort(WebServiceFeature... features) {
        return super.getPort(DesguaceJavaWSPort, DesguaceJavaWS.class, features);
    }

}
