
package gestor_taller.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * Fri Feb 07 20:05:15 CET 2014
 * Generated source version: 3.0.0-milestone1
 */

@XmlRootElement(name = "baja", namespace = "http://gestor_taller/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baja", namespace = "http://gestor_taller/")

public class Baja {

    @XmlElement(name = "tallerID")
    private java.lang.String tallerID;

    public java.lang.String getTallerID() {
        return this.tallerID;
    }

    public void setTallerID(java.lang.String newTallerID)  {
        this.tallerID = newTallerID;
    }

}

