
package gestor_taller.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * Fri Feb 07 20:05:15 CET 2014
 * Generated source version: 3.0.0-milestone1
 */

@XmlRootElement(name = "getOfertas", namespace = "http://gestor_taller/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOfertas", namespace = "http://gestor_taller/")

public class GetOfertas {

    @XmlElement(name = "listaPedidos")
    private java.lang.String listaPedidos;

    public java.lang.String getListaPedidos() {
        return this.listaPedidos;
    }

    public void setListaPedidos(java.lang.String newListaPedidos)  {
        this.listaPedidos = newListaPedidos;
    }

}

