package gestor_admin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-16T22:43:34.386+01:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebService(targetNamespace = "http://gestor_admin/", name = "AdminWS")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPedidos", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetPedidos")
    @WebMethod
    @ResponseWrapper(localName = "getPedidosResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetPedidosResponse")
    public java.lang.String getPedidos();

    @RequestWrapper(localName = "sendMail", targetNamespace = "http://gestor_admin/", className = "gestor_admin.SendMail")
    @WebMethod
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.SendMailResponse")
    public void sendMail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAltaDesguace", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetAltaDesguace")
    @WebMethod
    @ResponseWrapper(localName = "getAltaDesguaceResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetAltaDesguaceResponse")
    public java.lang.String getAltaDesguace();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTalleres", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetTalleres")
    @WebMethod
    @ResponseWrapper(localName = "getTalleresResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetTalleresResponse")
    public java.lang.String getTalleres();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addAccesoDesguace", targetNamespace = "http://gestor_admin/", className = "gestor_admin.AddAccesoDesguace")
    @WebMethod
    @ResponseWrapper(localName = "addAccesoDesguaceResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.AddAccesoDesguaceResponse")
    public java.lang.Boolean addAccesoDesguace(
        @WebParam(name = "ID", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "Registrar", targetNamespace = "http://gestor_admin/", className = "gestor_admin.Registrar")
    @WebMethod(operationName = "Registrar")
    @ResponseWrapper(localName = "RegistrarResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.RegistrarResponse")
    public java.lang.String registrar();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDesguacesAceptados", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetDesguacesAceptados")
    @WebMethod
    @ResponseWrapper(localName = "getDesguacesAceptadosResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetDesguacesAceptadosResponse")
    public java.lang.String getDesguacesAceptados();

	@WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDesguaces", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetDesguaces")
    @WebMethod
    @ResponseWrapper(localName = "getDesguacesResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetDesguacesResponse")
    public java.lang.String getDesguaces();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://gestor_admin/", className = "gestor_admin.Hello")
    @WebMethod
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.HelloResponse")
    public java.lang.String hello();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTalleresAceptados", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetTalleresAceptados")
    @WebMethod
    @ResponseWrapper(localName = "getTalleresAceptadosResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetTalleresAceptadosResponse")
    public java.lang.String getTalleresAceptados();

	@WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "darAccesoTaller", targetNamespace = "http://gestor_admin/", className = "gestor_admin.DarAccesoTaller")
    @WebMethod
    @ResponseWrapper(localName = "darAccesoTallerResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.DarAccesoTallerResponse")
    public java.lang.Boolean darAccesoTaller(
        @WebParam(name = "ID", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPedidoID", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetPedidoID")
    @WebMethod
    @ResponseWrapper(localName = "getPedidoIDResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetPedidoIDResponse")
    public java.lang.String getPedidoID(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAltaTalleres", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetAltaTalleres")
    @WebMethod
    @ResponseWrapper(localName = "getAltaTalleresResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetAltaTalleresResponse")
    public java.lang.String getAltaTalleres();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOfertasporPedido", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetOfertasporPedido")
    @WebMethod
    @ResponseWrapper(localName = "getOfertasporPedidoResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetOfertasporPedidoResponse")
    public java.lang.String getOfertasporPedido(
        @WebParam(name = "idPedido", targetNamespace = "")
        java.lang.String idPedido
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOfertas", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetOfertas")
    @WebMethod
    @ResponseWrapper(localName = "getOfertasResponse", targetNamespace = "http://gestor_admin/", className = "gestor_admin.GetOfertasResponse")
    public java.lang.String getOfertas();
}
