
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gestor_admin;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-09T22:07:33.048+01:00
 * Generated source version: 3.0.0-milestone1
 * 
 */

@javax.jws.WebService(
                      serviceName = "AdminWS",
                      portName = "AdminWSPort",
                      targetNamespace = "http://gestor_admin/",
                      wsdlLocation = "file:/C:/Users/Silvia/workspace/SOR/Gestor/WebContent/wsdl/adminws.wsdl",
                      endpointInterface = "gestor_admin.AdminWS")
                      
public class AdminWSImpl implements AdminWS {

    private static final Logger LOG = Logger.getLogger(AdminWSImpl.class.getName());

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#getPedidos(*
     */
    public java.lang.String getPedidos() { 
        LOG.info("Executing operation getPedidos");
        try {
            java.lang.String _return = "_return1724330893";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#sendMail(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public void sendMail(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation sendMail");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#getAltaDesguace(*
     */
    public java.lang.String getAltaDesguace() { 
        LOG.info("Executing operation getAltaDesguace");
        try {
            java.lang.String _return = "_return701646106";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#getTalleres(*
     */
    public java.lang.String getTalleres() { 
        LOG.info("Executing operation getTalleres");
        try {
            java.lang.String _return = "_return25908341";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#addAccesoDesguace(java.lang.String  id )*
     */
    public java.lang.Boolean addAccesoDesguace(java.lang.String id) { 
        LOG.info("Executing operation addAccesoDesguace");
        System.out.println(id);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#registrar(*
     */
    public java.lang.String registrar() { 
        LOG.info("Executing operation registrar");
        try {
            java.lang.String _return = "_return-1267407520";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#getDesguaces(*
     */
    public java.lang.String getDesguaces() { 
        LOG.info("Executing operation getDesguaces");
        try {
            java.lang.String _return = "_return1044718745";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#hello(*
     */
    public java.lang.String hello() { 
        LOG.info("Executing operation hello");
        try {
            java.lang.String _return = "_return-294820518";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#darAccesoTaller(java.lang.String  id )*
     */
    public java.lang.Boolean darAccesoTaller(java.lang.String id) { 
        LOG.info("Executing operation darAccesoTaller");
        System.out.println(id);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#getPedidoID(java.lang.String  id )*
     */
    public java.lang.String getPedidoID(java.lang.String id) { 
        LOG.info("Executing operation getPedidoID");
        System.out.println(id);
        try {
            java.lang.String _return = "_return-1667546886";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#getAltaTalleres(*
     */
    public java.lang.String getAltaTalleres() { 
        LOG.info("Executing operation getAltaTalleres");
        try {
            java.lang.String _return = "_return-1791222926";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#getOfertasporPedido(java.lang.String  idPedido )*
     */
    public java.lang.String getOfertasporPedido(java.lang.String idPedido) { 
        LOG.info("Executing operation getOfertasporPedido");
        System.out.println(idPedido);
        try {
            java.lang.String _return = "_return-1388612330";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gestor_admin.AdminWS#getOfertas(*
     */
    public java.lang.String getOfertas() { 
        LOG.info("Executing operation getOfertas");
        try {
            java.lang.String _return = "_return-915675819";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
