
package gestor_taller;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-04-08T17:50:45.941+02:00
 * Generated source version: 3.0.0-milestone1
 */

@WebFault(name = "JMSException", targetNamespace = "http://gestor_taller/")
public class JMSException_Exception extends Exception {
    
    private gestor_taller.JMSException jmsException;

    public JMSException_Exception() {
        super();
    }
    
    public JMSException_Exception(String message) {
        super(message);
    }
    
    public JMSException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public JMSException_Exception(String message, gestor_taller.JMSException jmsException) {
        super(message);
        this.jmsException = jmsException;
    }

    public JMSException_Exception(String message, gestor_taller.JMSException jmsException, Throwable cause) {
        super(message, cause);
        this.jmsException = jmsException;
    }

    public gestor_taller.JMSException getFaultInfo() {
        return this.jmsException;
    }
}
