
package gestor_taller;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-04-05T11:58:33.022+02:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
public final class TallerWS_TallerWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gestor_taller/", "TallerWS");

    private TallerWS_TallerWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TallerWS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TallerWS_Service ss = new TallerWS_Service(wsdlURL, SERVICE_NAME);
        TallerWS port = ss.getTallerWSPort();  
        
        {
        System.out.println("Invoking alta...");
        java.lang.String _alta_name = "_alta_name140103366";
        java.lang.String _alta_email = "_alta_email1216112385";
        java.lang.String _alta_address = "_alta_address-1808335760";
        java.lang.String _alta_city = "_alta_city1812559169";
        java.lang.String _alta_postalCode = "_alta_postalCode1881486846";
        java.lang.String _alta_telephone = "_alta_telephone645182352";
        boolean _alta__return = port.alta(_alta_name, _alta_email, _alta_address, _alta_city, _alta_postalCode, _alta_telephone);
        System.out.println("alta.result=" + _alta__return);


        }
        {
        System.out.println("Invoking cancelarPedido...");
        java.lang.String _cancelarPedido_idPedido = "_cancelarPedido_idPedido-53225063";
        java.lang.String _cancelarPedido_idTaller = "_cancelarPedido_idTaller-1009440873";
        java.lang.Boolean _cancelarPedido__return = port.cancelarPedido(_cancelarPedido_idPedido, _cancelarPedido_idTaller);
        System.out.println("cancelarPedido.result=" + _cancelarPedido__return);


        }
        {
        System.out.println("Invoking generarClaveReto...");
        java.lang.String _generarClaveReto_idTaller = "_generarClaveReto_idTaller644807013";
        java.lang.String _generarClaveReto__return = port.generarClaveReto(_generarClaveReto_idTaller);
        System.out.println("generarClaveReto.result=" + _generarClaveReto__return);


        }
        {
        System.out.println("Invoking cambiarEstadoPedido...");
        int _cambiarEstadoPedido_estado = 925553905;
        java.lang.String _cambiarEstadoPedido_id = "_cambiarEstadoPedido_id-493753324";
        java.lang.String _cambiarEstadoPedido_idTaller = "_cambiarEstadoPedido_idTaller-606795970";
        java.lang.Boolean _cambiarEstadoPedido__return = port.cambiarEstadoPedido(_cambiarEstadoPedido_estado, _cambiarEstadoPedido_id, _cambiarEstadoPedido_idTaller);
        System.out.println("cambiarEstadoPedido.result=" + _cambiarEstadoPedido__return);


        }
        {
        System.out.println("Invoking getPedidos...");
        java.lang.String _getPedidos_id = "_getPedidos_id470163258";
        java.lang.String _getPedidos__return = port.getPedidos(_getPedidos_id);
        System.out.println("getPedidos.result=" + _getPedidos__return);


        }
        {
        System.out.println("Invoking baja...");
        java.lang.String _baja_tallerID = "_baja_tallerID1835480261";
        java.lang.Boolean _baja__return = port.baja(_baja_tallerID);
        System.out.println("baja.result=" + _baja__return);


        }
        {
        System.out.println("Invoking hello...");
        java.lang.String _hello__return = port.hello();
        System.out.println("hello.result=" + _hello__return);


        }
        {
        System.out.println("Invoking modificar...");
        java.lang.String _modificar_id = "_modificar_id-1589985515";
        java.lang.String _modificar_name = "_modificar_name-98547664";
        java.lang.String _modificar_email = "_modificar_email-415083600";
        java.lang.String _modificar_address = "_modificar_address149247793";
        java.lang.String _modificar_city = "_modificar_city-927499904";
        java.lang.String _modificar_postalCode = "_modificar_postalCode-599460587";
        java.lang.String _modificar_telephone = "_modificar_telephone-1579226125";
        boolean _modificar__return = port.modificar(_modificar_id, _modificar_name, _modificar_email, _modificar_address, _modificar_city, _modificar_postalCode, _modificar_telephone);
        System.out.println("modificar.result=" + _modificar__return);


        }
        {
        System.out.println("Invoking checkActivacion...");
        java.lang.String _checkActivacion_mail = "_checkActivacion_mail284801929";
        java.lang.String _checkActivacion__return = port.checkActivacion(_checkActivacion_mail);
        System.out.println("checkActivacion.result=" + _checkActivacion__return);


        }
        {
        System.out.println("Invoking getOfertas...");
        java.lang.String _getOfertas_listaPedidos = "_getOfertas_listaPedidos-1685896566";
        java.lang.String _getOfertas_idTaller = "_getOfertas_idTaller1402478876";
        java.lang.String _getOfertas__return = port.getOfertas(_getOfertas_listaPedidos, _getOfertas_idTaller);
        System.out.println("getOfertas.result=" + _getOfertas__return);


        }
        {
        System.out.println("Invoking aceptarOferta...");
        java.lang.String _aceptarOferta_id = "_aceptarOferta_id1263834477";
        java.lang.String _aceptarOferta_idTaller = "_aceptarOferta_idTaller1390974026";
        java.lang.Boolean _aceptarOferta__return = port.aceptarOferta(_aceptarOferta_id, _aceptarOferta_idTaller);
        System.out.println("aceptarOferta.result=" + _aceptarOferta__return);


        }
        {
        System.out.println("Invoking nuevoPedido...");
        java.lang.String _nuevoPedido_pedido = "_nuevoPedido_pedido1875692704";
        java.lang.String _nuevoPedido_idTaller = "_nuevoPedido_idTaller-2055806194";
        try {
            java.lang.String _nuevoPedido__return = port.nuevoPedido(_nuevoPedido_pedido, _nuevoPedido_idTaller);
            System.out.println("nuevoPedido.result=" + _nuevoPedido__return);

        } catch (JMSException_Exception e) { 
            System.out.println("Expected exception: JMSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking rechazarOferta...");
        java.lang.String _rechazarOferta_id = "_rechazarOferta_id1418212676";
        java.lang.String _rechazarOferta_idTaller = "_rechazarOferta_idTaller2111539790";
        java.lang.Boolean _rechazarOferta__return = port.rechazarOferta(_rechazarOferta_id, _rechazarOferta_idTaller);
        System.out.println("rechazarOferta.result=" + _rechazarOferta__return);


        }

        System.exit(0);
    }

}
