
package gestor_taller;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-04-14T10:20:49.109+02:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
public final class TallerWS_TallerWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gestor_taller/", "TallerWS");

    private TallerWS_TallerWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TallerWS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TallerWS_Service ss = new TallerWS_Service(wsdlURL, SERVICE_NAME);
        TallerWS port = ss.getTallerWSPort();  
        
        {
        System.out.println("Invoking alta...");
        java.lang.String _alta_name = "_alta_name1929514009";
        java.lang.String _alta_email = "_alta_email1944497369";
        java.lang.String _alta_address = "_alta_address2088590539";
        java.lang.String _alta_city = "_alta_city-45878315";
        java.lang.String _alta_postalCode = "_alta_postalCode442587654";
        java.lang.String _alta_telephone = "_alta_telephone-982697186";
        boolean _alta__return = port.alta(_alta_name, _alta_email, _alta_address, _alta_city, _alta_postalCode, _alta_telephone);
        System.out.println("alta.result=" + _alta__return);


        }
        {
        System.out.println("Invoking cancelarPedido...");
        java.lang.String _cancelarPedido_idPedido = "_cancelarPedido_idPedido-942596507";
        java.lang.String _cancelarPedido_idTaller = "_cancelarPedido_idTaller-1445545480";
        java.lang.String _cancelarPedido_password = "_cancelarPedido_password-454600577";
        java.lang.Boolean _cancelarPedido__return = port.cancelarPedido(_cancelarPedido_idPedido, _cancelarPedido_idTaller, _cancelarPedido_password);
        System.out.println("cancelarPedido.result=" + _cancelarPedido__return);


        }
        {
        System.out.println("Invoking generarClaveReto...");
        java.lang.String _generarClaveReto_idTaller = "_generarClaveReto_idTaller-14635643";
        java.lang.String _generarClaveReto_password = "_generarClaveReto_password-280381522";
        java.lang.String _generarClaveReto__return = port.generarClaveReto(_generarClaveReto_idTaller, _generarClaveReto_password);
        System.out.println("generarClaveReto.result=" + _generarClaveReto__return);


        }
        {
        System.out.println("Invoking cambiarEstadoPedido...");
        java.lang.String _cambiarEstadoPedido_idTaller = "_cambiarEstadoPedido_idTaller-1881803074";
        java.lang.String _cambiarEstadoPedido_password = "_cambiarEstadoPedido_password-93562012";
        int _cambiarEstadoPedido_estado = 2070051950;
        java.lang.String _cambiarEstadoPedido_id = "_cambiarEstadoPedido_id1073729622";
        java.lang.Boolean _cambiarEstadoPedido__return = port.cambiarEstadoPedido(_cambiarEstadoPedido_idTaller, _cambiarEstadoPedido_password, _cambiarEstadoPedido_estado, _cambiarEstadoPedido_id);
        System.out.println("cambiarEstadoPedido.result=" + _cambiarEstadoPedido__return);


        }
        {
        System.out.println("Invoking getPedidos...");
        java.lang.String _getPedidos_idTaller = "_getPedidos_idTaller284249829";
        java.lang.String _getPedidos_password = "_getPedidos_password926780418";
        java.lang.String _getPedidos__return = port.getPedidos(_getPedidos_idTaller, _getPedidos_password);
        System.out.println("getPedidos.result=" + _getPedidos__return);


        }
        {
        System.out.println("Invoking baja...");
        java.lang.String _baja_tallerID = "_baja_tallerID541730622";
        java.lang.String _baja_password = "_baja_password1967513181";
        java.lang.Boolean _baja__return = port.baja(_baja_tallerID, _baja_password);
        System.out.println("baja.result=" + _baja__return);


        }
        {
        System.out.println("Invoking hello...");
        java.lang.String _hello__return = port.hello();
        System.out.println("hello.result=" + _hello__return);


        }
        {
        System.out.println("Invoking modificar...");
        java.lang.String _modificar_id = "_modificar_id-1755352471";
        java.lang.String _modificar_password = "_modificar_password103074472";
        java.lang.String _modificar_name = "_modificar_name-1776600991";
        java.lang.String _modificar_email = "_modificar_email473134021";
        java.lang.String _modificar_address = "_modificar_address-638719446";
        java.lang.String _modificar_city = "_modificar_city1494521210";
        java.lang.String _modificar_postalCode = "_modificar_postalCode1028195729";
        java.lang.String _modificar_telephone = "_modificar_telephone-391433336";
        boolean _modificar__return = port.modificar(_modificar_id, _modificar_password, _modificar_name, _modificar_email, _modificar_address, _modificar_city, _modificar_postalCode, _modificar_telephone);
        System.out.println("modificar.result=" + _modificar__return);


        }
        {
        System.out.println("Invoking checkActivacion...");
        java.lang.String _checkActivacion_email = "_checkActivacion_email-762471477";
        java.lang.String _checkActivacion_mail = "_checkActivacion_mail799737988";
        java.lang.String _checkActivacion__return = port.checkActivacion(_checkActivacion_email, _checkActivacion_mail);
        System.out.println("checkActivacion.result=" + _checkActivacion__return);


        }
        {
        System.out.println("Invoking getOfertas...");
        java.lang.String _getOfertas_listaPedidos = "_getOfertas_listaPedidos-1866485673";
        java.lang.String _getOfertas_idTaller = "_getOfertas_idTaller378970572";
        java.lang.String _getOfertas_password = "_getOfertas_password-372693028";
        java.lang.String _getOfertas__return = port.getOfertas(_getOfertas_listaPedidos, _getOfertas_idTaller, _getOfertas_password);
        System.out.println("getOfertas.result=" + _getOfertas__return);


        }
        {
        System.out.println("Invoking aceptarOferta...");
        java.lang.String _aceptarOferta_id = "_aceptarOferta_id1918651154";
        java.lang.String _aceptarOferta_idTaller = "_aceptarOferta_idTaller916335314";
        java.lang.String _aceptarOferta_password = "_aceptarOferta_password101860180";
        java.lang.Boolean _aceptarOferta__return = port.aceptarOferta(_aceptarOferta_id, _aceptarOferta_idTaller, _aceptarOferta_password);
        System.out.println("aceptarOferta.result=" + _aceptarOferta__return);


        }
        {
        System.out.println("Invoking nuevoPedido...");
        java.lang.String _nuevoPedido_pedido = "_nuevoPedido_pedido-1329560006";
        java.lang.String _nuevoPedido_idTaller = "_nuevoPedido_idTaller356908606";
        java.lang.String _nuevoPedido_password = "_nuevoPedido_password302335158";
        try {
            java.lang.String _nuevoPedido__return = port.nuevoPedido(_nuevoPedido_pedido, _nuevoPedido_idTaller, _nuevoPedido_password);
            System.out.println("nuevoPedido.result=" + _nuevoPedido__return);

        } catch (JMSException_Exception e) { 
            System.out.println("Expected exception: JMSException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking rechazarOferta...");
        java.lang.String _rechazarOferta_id = "_rechazarOferta_id1308082234";
        java.lang.String _rechazarOferta_idTaller = "_rechazarOferta_idTaller-149453643";
        java.lang.String _rechazarOferta_password = "_rechazarOferta_password-1414364983";
        java.lang.Boolean _rechazarOferta__return = port.rechazarOferta(_rechazarOferta_id, _rechazarOferta_idTaller, _rechazarOferta_password);
        System.out.println("rechazarOferta.result=" + _rechazarOferta__return);


        }

        System.exit(0);
    }

}
