
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.apache.juddi.v3_service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-04-05T12:43:16.755+02:00
 * Generated source version: 3.0.0-milestone1
 * 
 */

@javax.jws.WebService(
                      serviceName = "JUDDIApiService",
                      portName = "JUDDIApiImplPort",
                      targetNamespace = "urn:juddi-apache-org:v3_service",
                      wsdlLocation = "http://localhost:8081/juddiv3/services/juddi-api?wsdl",
                      endpointInterface = "org.apache.juddi.v3_service.JUDDIApiPortType")
                      
public class JUDDIApiPortTypeImpl implements JUDDIApiPortType {

    private static final Logger LOG = Logger.getLogger(JUDDIApiPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#getPublisherDetail(org.apache.juddi.api_v3.GetPublisherDetail  body )*
     */
    public org.apache.juddi.api_v3.PublisherDetail getPublisherDetail(org.apache.juddi.api_v3.GetPublisherDetail body) { 
        LOG.info("Executing operation getPublisherDetail");
        System.out.println(body);
        try {
            org.apache.juddi.api_v3.PublisherDetail _return = new org.apache.juddi.api_v3.PublisherDetail();
            java.util.List<org.apache.juddi.api_v3.Publisher> _returnPublisher = new java.util.ArrayList<org.apache.juddi.api_v3.Publisher>();
            org.apache.juddi.api_v3.Publisher _returnPublisherVal1 = new org.apache.juddi.api_v3.Publisher();
            _returnPublisherVal1.setPublisherName("PublisherName1052235210");
            _returnPublisherVal1.setEmailAddress("EmailAddress15423039");
            _returnPublisherVal1.setIsAdmin("IsAdmin-173571557");
            _returnPublisherVal1.setIsEnabled("IsEnabled1464901426");
            _returnPublisherVal1.setMaxBindingsPerService(Integer.valueOf(2052614313));
            _returnPublisherVal1.setMaxBusinesses(Integer.valueOf(-2049929599));
            _returnPublisherVal1.setMaxServicePerBusiness(Integer.valueOf(-1001729677));
            _returnPublisherVal1.setMaxTModels(Integer.valueOf(-671999579));
            java.util.List<org.w3._2000._09.xmldsig.SignatureType> _returnPublisherVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
            _returnPublisherVal1.getSignature().addAll(_returnPublisherVal1Signature);
            _returnPublisherVal1.setAuthorizedName("AuthorizedName1280622042");
            _returnPublisher.add(_returnPublisherVal1);
            _return.getPublisher().addAll(_returnPublisher);
            _return.setTruncated(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#deleteClientSubscriptionInfo(org.apache.juddi.api_v3.DeleteClientSubscriptionInfo  body )*
     */
    public void deleteClientSubscriptionInfo(org.apache.juddi.api_v3.DeleteClientSubscriptionInfo body) { 
        LOG.info("Executing operation deleteClientSubscriptionInfo");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#getAllPublisherDetail(org.apache.juddi.api_v3.GetAllPublisherDetail  body )*
     */
    public org.apache.juddi.api_v3.PublisherDetail getAllPublisherDetail(org.apache.juddi.api_v3.GetAllPublisherDetail body) { 
        LOG.info("Executing operation getAllPublisherDetail");
        System.out.println(body);
        try {
            org.apache.juddi.api_v3.PublisherDetail _return = new org.apache.juddi.api_v3.PublisherDetail();
            java.util.List<org.apache.juddi.api_v3.Publisher> _returnPublisher = new java.util.ArrayList<org.apache.juddi.api_v3.Publisher>();
            org.apache.juddi.api_v3.Publisher _returnPublisherVal1 = new org.apache.juddi.api_v3.Publisher();
            _returnPublisherVal1.setPublisherName("PublisherName2139122039");
            _returnPublisherVal1.setEmailAddress("EmailAddress-1551017641");
            _returnPublisherVal1.setIsAdmin("IsAdmin-1747735033");
            _returnPublisherVal1.setIsEnabled("IsEnabled-425146463");
            _returnPublisherVal1.setMaxBindingsPerService(Integer.valueOf(1960522577));
            _returnPublisherVal1.setMaxBusinesses(Integer.valueOf(-1390784927));
            _returnPublisherVal1.setMaxServicePerBusiness(Integer.valueOf(-1831075285));
            _returnPublisherVal1.setMaxTModels(Integer.valueOf(-1295141846));
            java.util.List<org.w3._2000._09.xmldsig.SignatureType> _returnPublisherVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
            _returnPublisherVal1.getSignature().addAll(_returnPublisherVal1Signature);
            _returnPublisherVal1.setAuthorizedName("AuthorizedName1954744843");
            _returnPublisher.add(_returnPublisherVal1);
            _return.getPublisher().addAll(_returnPublisher);
            _return.setTruncated(Boolean.valueOf(false));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#saveClerk(org.apache.juddi.api_v3.SaveClerkInfo  body )*
     */
    public org.apache.juddi.api_v3.ClerkDetail saveClerk(org.apache.juddi.api_v3.SaveClerkInfo body) { 
        LOG.info("Executing operation saveClerk");
        System.out.println(body);
        try {
            org.apache.juddi.api_v3.ClerkDetail _return = new org.apache.juddi.api_v3.ClerkDetail();
            java.util.List<org.apache.juddi.api_v3.Clerk> _returnClerk = new java.util.ArrayList<org.apache.juddi.api_v3.Clerk>();
            org.apache.juddi.api_v3.Clerk _returnClerkVal1 = new org.apache.juddi.api_v3.Clerk();
            _returnClerkVal1.setName("Name890665664");
            org.apache.juddi.api_v3.Node _returnClerkVal1Node = new org.apache.juddi.api_v3.Node();
            _returnClerkVal1Node.setName("Name-1628687405");
            _returnClerkVal1Node.setClientName("ClientName-795799468");
            _returnClerkVal1Node.setDescription("Description-1899822286");
            _returnClerkVal1Node.setCustodyTransferUrl("CustodyTransferUrl-1987664612");
            _returnClerkVal1Node.setInquiryUrl("InquiryUrl-1226882499");
            _returnClerkVal1Node.setPublishUrl("PublishUrl1874140803");
            _returnClerkVal1Node.setSecurityUrl("SecurityUrl2059220511");
            _returnClerkVal1Node.setSubscriptionUrl("SubscriptionUrl-600759528");
            _returnClerkVal1Node.setSubscriptionListenerUrl("SubscriptionListenerUrl-940073987");
            _returnClerkVal1Node.setJuddiApiUrl("JuddiApiUrl850758876");
            _returnClerkVal1Node.setProxyTransport("ProxyTransport-1221612713");
            _returnClerkVal1Node.setFactoryInitial("FactoryInitial49039602");
            _returnClerkVal1Node.setFactoryURLPkgs("FactoryURLPkgs366596276");
            _returnClerkVal1Node.setFactoryNamingProvider("FactoryNamingProvider2108349970");
            _returnClerkVal1.setNode(_returnClerkVal1Node);
            _returnClerkVal1.setPublisher("Publisher-1511194142");
            _returnClerkVal1.setPassword("Password-1123928716");
            _returnClerk.add(_returnClerkVal1);
            _return.getClerk().addAll(_returnClerk);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#deletePublisher(org.apache.juddi.api_v3.DeletePublisher  body )*
     */
    public void deletePublisher(org.apache.juddi.api_v3.DeletePublisher body) { 
        LOG.info("Executing operation deletePublisher");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#savePublisher(org.apache.juddi.api_v3.SavePublisher  body )*
     */
    public org.apache.juddi.api_v3.PublisherDetail savePublisher(org.apache.juddi.api_v3.SavePublisher body) { 
        LOG.info("Executing operation savePublisher");
        System.out.println(body);
        try {
            org.apache.juddi.api_v3.PublisherDetail _return = new org.apache.juddi.api_v3.PublisherDetail();
            java.util.List<org.apache.juddi.api_v3.Publisher> _returnPublisher = new java.util.ArrayList<org.apache.juddi.api_v3.Publisher>();
            org.apache.juddi.api_v3.Publisher _returnPublisherVal1 = new org.apache.juddi.api_v3.Publisher();
            _returnPublisherVal1.setPublisherName("PublisherName761455196");
            _returnPublisherVal1.setEmailAddress("EmailAddress602738189");
            _returnPublisherVal1.setIsAdmin("IsAdmin1499358598");
            _returnPublisherVal1.setIsEnabled("IsEnabled370788437");
            _returnPublisherVal1.setMaxBindingsPerService(Integer.valueOf(728172004));
            _returnPublisherVal1.setMaxBusinesses(Integer.valueOf(-926906131));
            _returnPublisherVal1.setMaxServicePerBusiness(Integer.valueOf(1405506429));
            _returnPublisherVal1.setMaxTModels(Integer.valueOf(1078860510));
            java.util.List<org.w3._2000._09.xmldsig.SignatureType> _returnPublisherVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
            _returnPublisherVal1.getSignature().addAll(_returnPublisherVal1Signature);
            _returnPublisherVal1.setAuthorizedName("AuthorizedName507730175");
            _returnPublisher.add(_returnPublisherVal1);
            _return.getPublisher().addAll(_returnPublisher);
            _return.setTruncated(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#saveNode(org.apache.juddi.api_v3.SaveNoodeInfo  body )*
     */
    public org.apache.juddi.api_v3.NodeDetail saveNode(org.apache.juddi.api_v3.SaveNoodeInfo body) { 
        LOG.info("Executing operation saveNode");
        System.out.println(body);
        try {
            org.apache.juddi.api_v3.NodeDetail _return = new org.apache.juddi.api_v3.NodeDetail();
            java.util.List<org.apache.juddi.api_v3.Node> _returnNode = new java.util.ArrayList<org.apache.juddi.api_v3.Node>();
            org.apache.juddi.api_v3.Node _returnNodeVal1 = new org.apache.juddi.api_v3.Node();
            _returnNodeVal1.setName("Name2090759784");
            _returnNodeVal1.setClientName("ClientName-1112383792");
            _returnNodeVal1.setDescription("Description1601478969");
            _returnNodeVal1.setCustodyTransferUrl("CustodyTransferUrl1497957579");
            _returnNodeVal1.setInquiryUrl("InquiryUrl2053295491");
            _returnNodeVal1.setPublishUrl("PublishUrl1559906180");
            _returnNodeVal1.setSecurityUrl("SecurityUrl-1695389621");
            _returnNodeVal1.setSubscriptionUrl("SubscriptionUrl1659371976");
            _returnNodeVal1.setSubscriptionListenerUrl("SubscriptionListenerUrl-175402215");
            _returnNodeVal1.setJuddiApiUrl("JuddiApiUrl1306354004");
            _returnNodeVal1.setProxyTransport("ProxyTransport103745967");
            _returnNodeVal1.setFactoryInitial("FactoryInitial-314341012");
            _returnNodeVal1.setFactoryURLPkgs("FactoryURLPkgs1335531065");
            _returnNodeVal1.setFactoryNamingProvider("FactoryNamingProvider-632423623");
            _returnNode.add(_returnNodeVal1);
            _return.getNode().addAll(_returnNode);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#adminDeleteTmodel(org.uddi.api_v3.DeleteTModel  body )*
     */
    public void adminDeleteTmodel(org.uddi.api_v3.DeleteTModel body) { 
        LOG.info("Executing operation adminDeleteTmodel");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#saveClientSubscriptionInfo(org.apache.juddi.api_v3.SaveClientSubscriptionInfo  body )*
     */
    public org.apache.juddi.api_v3.ClientSubscriptionInfoDetail saveClientSubscriptionInfo(org.apache.juddi.api_v3.SaveClientSubscriptionInfo body) { 
        LOG.info("Executing operation saveClientSubscriptionInfo");
        System.out.println(body);
        try {
            org.apache.juddi.api_v3.ClientSubscriptionInfoDetail _return = new org.apache.juddi.api_v3.ClientSubscriptionInfoDetail();
            java.util.List<org.apache.juddi.api_v3.ClientSubscriptionInfo> _returnClientSubscriptionInfo = new java.util.ArrayList<org.apache.juddi.api_v3.ClientSubscriptionInfo>();
            org.apache.juddi.api_v3.ClientSubscriptionInfo _returnClientSubscriptionInfoVal1 = new org.apache.juddi.api_v3.ClientSubscriptionInfo();
            _returnClientSubscriptionInfoVal1.setSubscriptionKey("SubscriptionKey764577141");
            org.apache.juddi.api_v3.Clerk _returnClientSubscriptionInfoVal1FromClerk = new org.apache.juddi.api_v3.Clerk();
            _returnClientSubscriptionInfoVal1FromClerk.setName("Name488721132");
            org.apache.juddi.api_v3.Node _returnClientSubscriptionInfoVal1FromClerkNode = new org.apache.juddi.api_v3.Node();
            _returnClientSubscriptionInfoVal1FromClerkNode.setName("Name-700974167");
            _returnClientSubscriptionInfoVal1FromClerkNode.setClientName("ClientName2013431477");
            _returnClientSubscriptionInfoVal1FromClerkNode.setDescription("Description-162583465");
            _returnClientSubscriptionInfoVal1FromClerkNode.setCustodyTransferUrl("CustodyTransferUrl191520015");
            _returnClientSubscriptionInfoVal1FromClerkNode.setInquiryUrl("InquiryUrl1772460570");
            _returnClientSubscriptionInfoVal1FromClerkNode.setPublishUrl("PublishUrl1683657203");
            _returnClientSubscriptionInfoVal1FromClerkNode.setSecurityUrl("SecurityUrl-1999865589");
            _returnClientSubscriptionInfoVal1FromClerkNode.setSubscriptionUrl("SubscriptionUrl-983875859");
            _returnClientSubscriptionInfoVal1FromClerkNode.setSubscriptionListenerUrl("SubscriptionListenerUrl1586455965");
            _returnClientSubscriptionInfoVal1FromClerkNode.setJuddiApiUrl("JuddiApiUrl-1315520468");
            _returnClientSubscriptionInfoVal1FromClerkNode.setProxyTransport("ProxyTransport-287986984");
            _returnClientSubscriptionInfoVal1FromClerkNode.setFactoryInitial("FactoryInitial1571594490");
            _returnClientSubscriptionInfoVal1FromClerkNode.setFactoryURLPkgs("FactoryURLPkgs951230037");
            _returnClientSubscriptionInfoVal1FromClerkNode.setFactoryNamingProvider("FactoryNamingProvider434988107");
            _returnClientSubscriptionInfoVal1FromClerk.setNode(_returnClientSubscriptionInfoVal1FromClerkNode);
            _returnClientSubscriptionInfoVal1FromClerk.setPublisher("Publisher1031730540");
            _returnClientSubscriptionInfoVal1FromClerk.setPassword("Password-1684981182");
            _returnClientSubscriptionInfoVal1.setFromClerk(_returnClientSubscriptionInfoVal1FromClerk);
            org.apache.juddi.api_v3.Clerk _returnClientSubscriptionInfoVal1ToClerk = new org.apache.juddi.api_v3.Clerk();
            _returnClientSubscriptionInfoVal1ToClerk.setName("Name-851659154");
            org.apache.juddi.api_v3.Node _returnClientSubscriptionInfoVal1ToClerkNode = new org.apache.juddi.api_v3.Node();
            _returnClientSubscriptionInfoVal1ToClerkNode.setName("Name2038145491");
            _returnClientSubscriptionInfoVal1ToClerkNode.setClientName("ClientName781015531");
            _returnClientSubscriptionInfoVal1ToClerkNode.setDescription("Description258289141");
            _returnClientSubscriptionInfoVal1ToClerkNode.setCustodyTransferUrl("CustodyTransferUrl-1268898995");
            _returnClientSubscriptionInfoVal1ToClerkNode.setInquiryUrl("InquiryUrl95238144");
            _returnClientSubscriptionInfoVal1ToClerkNode.setPublishUrl("PublishUrl1968864587");
            _returnClientSubscriptionInfoVal1ToClerkNode.setSecurityUrl("SecurityUrl1471137062");
            _returnClientSubscriptionInfoVal1ToClerkNode.setSubscriptionUrl("SubscriptionUrl1889308168");
            _returnClientSubscriptionInfoVal1ToClerkNode.setSubscriptionListenerUrl("SubscriptionListenerUrl632511276");
            _returnClientSubscriptionInfoVal1ToClerkNode.setJuddiApiUrl("JuddiApiUrl-789639202");
            _returnClientSubscriptionInfoVal1ToClerkNode.setProxyTransport("ProxyTransport1675657423");
            _returnClientSubscriptionInfoVal1ToClerkNode.setFactoryInitial("FactoryInitial-885844200");
            _returnClientSubscriptionInfoVal1ToClerkNode.setFactoryURLPkgs("FactoryURLPkgs-968540044");
            _returnClientSubscriptionInfoVal1ToClerkNode.setFactoryNamingProvider("FactoryNamingProvider-1516004816");
            _returnClientSubscriptionInfoVal1ToClerk.setNode(_returnClientSubscriptionInfoVal1ToClerkNode);
            _returnClientSubscriptionInfoVal1ToClerk.setPublisher("Publisher20760600");
            _returnClientSubscriptionInfoVal1ToClerk.setPassword("Password-24731315");
            _returnClientSubscriptionInfoVal1.setToClerk(_returnClientSubscriptionInfoVal1ToClerk);
            _returnClientSubscriptionInfoVal1.setLastModified(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-05T12:43:16.765+02:00"));
            _returnClientSubscriptionInfo.add(_returnClientSubscriptionInfoVal1);
            _return.getClientSubscriptionInfo().addAll(_returnClientSubscriptionInfo);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apache.juddi.v3_service.JUDDIApiPortType#invokeSyncSubscription(org.apache.juddi.api_v3.SyncSubscription  body )*
     */
    public org.apache.juddi.api_v3.SyncSubscriptionDetail invokeSyncSubscription(org.apache.juddi.api_v3.SyncSubscription body) { 
        LOG.info("Executing operation invokeSyncSubscription");
        System.out.println(body);
        try {
            org.apache.juddi.api_v3.SyncSubscriptionDetail _return = new org.apache.juddi.api_v3.SyncSubscriptionDetail();
            java.util.List<org.uddi.sub_v3.SubscriptionResultsList> _returnList = new java.util.ArrayList<org.uddi.sub_v3.SubscriptionResultsList>();
            org.uddi.sub_v3.SubscriptionResultsList _returnListVal1 = new org.uddi.sub_v3.SubscriptionResultsList();
            _returnListVal1.setChunkToken("ChunkToken-1721024613");
            org.uddi.sub_v3.CoveragePeriod _returnListVal1CoveragePeriod = new org.uddi.sub_v3.CoveragePeriod();
            _returnListVal1CoveragePeriod.setStartPoint(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-05T12:43:16.766+02:00"));
            _returnListVal1CoveragePeriod.setEndPoint(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-04-05T12:43:16.766+02:00"));
            _returnListVal1.setCoveragePeriod(_returnListVal1CoveragePeriod);
            org.uddi.sub_v3.Subscription _returnListVal1Subscription = new org.uddi.sub_v3.Subscription();
            _returnListVal1Subscription.setSubscriptionKey("SubscriptionKey-1656700142");
            org.uddi.sub_v3.SubscriptionFilter _returnListVal1SubscriptionSubscriptionFilter = new org.uddi.sub_v3.SubscriptionFilter();
            org.uddi.api_v3.FindBinding _returnListVal1SubscriptionSubscriptionFilterFindBinding = new org.uddi.api_v3.FindBinding();
            _returnListVal1SubscriptionSubscriptionFilterFindBinding.setAuthInfo("AuthInfo-100419880");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindBindingFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindBindingFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindBinding.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindQualifiers);
            org.uddi.api_v3.TModelBag _returnListVal1SubscriptionSubscriptionFilterFindBindingTModelBag = new org.uddi.api_v3.TModelBag();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindBindingTModelBagTModelKey = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingTModelBag.getTModelKey().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBindingTModelBagTModelKey);
            _returnListVal1SubscriptionSubscriptionFilterFindBinding.setTModelBag(_returnListVal1SubscriptionSubscriptionFilterFindBindingTModelBag);
            org.uddi.api_v3.FindTModel _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel = new org.uddi.api_v3.FindTModel();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel.setAuthInfo("AuthInfo-39888895");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelFindQualifiers);
            org.uddi.api_v3.Name _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelName = new org.uddi.api_v3.Name();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelName.setValue("Value-2084589779");
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelName.setLang("Lang-1701485834");
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel.setName(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelName);
            org.uddi.api_v3.IdentifierBag _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelIdentifierBag = new org.uddi.api_v3.IdentifierBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelIdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelIdentifierBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelIdentifierBagKeyedReference);
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel.setIdentifierBag(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelIdentifierBag);
            org.uddi.api_v3.CategoryBag _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelCategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelCategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelCategoryBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelCategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelCategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelCategoryBag.getKeyedReferenceGroup().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelCategoryBagKeyedReferenceGroup);
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel.setCategoryBag(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModelCategoryBag);
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel.setMaxRows(Integer.valueOf(1260507227));
            _returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel.setListHead(Integer.valueOf(-1997020016));
            _returnListVal1SubscriptionSubscriptionFilterFindBinding.setFindTModel(_returnListVal1SubscriptionSubscriptionFilterFindBindingFindTModel);
            org.uddi.api_v3.CategoryBag _returnListVal1SubscriptionSubscriptionFilterFindBindingCategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindBindingCategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingCategoryBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBindingCategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnListVal1SubscriptionSubscriptionFilterFindBindingCategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnListVal1SubscriptionSubscriptionFilterFindBindingCategoryBag.getKeyedReferenceGroup().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBindingCategoryBagKeyedReferenceGroup);
            _returnListVal1SubscriptionSubscriptionFilterFindBinding.setCategoryBag(_returnListVal1SubscriptionSubscriptionFilterFindBindingCategoryBag);
            _returnListVal1SubscriptionSubscriptionFilterFindBinding.setMaxRows(Integer.valueOf(-2120294681));
            _returnListVal1SubscriptionSubscriptionFilterFindBinding.setServiceKey("ServiceKey-167118722");
            _returnListVal1SubscriptionSubscriptionFilterFindBinding.setListHead(Integer.valueOf(975608421));
            _returnListVal1SubscriptionSubscriptionFilter.setFindBinding(_returnListVal1SubscriptionSubscriptionFilterFindBinding);
            org.uddi.api_v3.FindBusiness _returnListVal1SubscriptionSubscriptionFilterFindBusiness = new org.uddi.api_v3.FindBusiness();
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setAuthInfo("AuthInfo-1861875961");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindQualifiers);
            java.util.List<org.uddi.api_v3.Name> _returnListVal1SubscriptionSubscriptionFilterFindBusinessName = new java.util.ArrayList<org.uddi.api_v3.Name>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.getName().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessName);
            org.uddi.api_v3.IdentifierBag _returnListVal1SubscriptionSubscriptionFilterFindBusinessIdentifierBag = new org.uddi.api_v3.IdentifierBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindBusinessIdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessIdentifierBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessIdentifierBagKeyedReference);
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setIdentifierBag(_returnListVal1SubscriptionSubscriptionFilterFindBusinessIdentifierBag);
            org.uddi.api_v3.CategoryBag _returnListVal1SubscriptionSubscriptionFilterFindBusinessCategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindBusinessCategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessCategoryBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessCategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnListVal1SubscriptionSubscriptionFilterFindBusinessCategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessCategoryBag.getKeyedReferenceGroup().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessCategoryBagKeyedReferenceGroup);
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setCategoryBag(_returnListVal1SubscriptionSubscriptionFilterFindBusinessCategoryBag);
            org.uddi.api_v3.TModelBag _returnListVal1SubscriptionSubscriptionFilterFindBusinessTModelBag = new org.uddi.api_v3.TModelBag();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindBusinessTModelBagTModelKey = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessTModelBag.getTModelKey().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessTModelBagTModelKey);
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setTModelBag(_returnListVal1SubscriptionSubscriptionFilterFindBusinessTModelBag);
            org.uddi.api_v3.FindTModel _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel = new org.uddi.api_v3.FindTModel();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel.setAuthInfo("AuthInfo846320726");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelFindQualifiers);
            org.uddi.api_v3.Name _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelName = new org.uddi.api_v3.Name();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelName.setValue("Value287199822");
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelName.setLang("Lang1875534967");
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel.setName(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelName);
            org.uddi.api_v3.IdentifierBag _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelIdentifierBag = new org.uddi.api_v3.IdentifierBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelIdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelIdentifierBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelIdentifierBagKeyedReference);
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel.setIdentifierBag(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelIdentifierBag);
            org.uddi.api_v3.CategoryBag _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelCategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelCategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelCategoryBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelCategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelCategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelCategoryBag.getKeyedReferenceGroup().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelCategoryBagKeyedReferenceGroup);
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel.setCategoryBag(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModelCategoryBag);
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel.setMaxRows(Integer.valueOf(1558677018));
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel.setListHead(Integer.valueOf(2094378429));
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setFindTModel(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindTModel);
            org.uddi.api_v3.DiscoveryURLs _returnListVal1SubscriptionSubscriptionFilterFindBusinessDiscoveryURLs = new org.uddi.api_v3.DiscoveryURLs();
            java.util.List<org.uddi.api_v3.DiscoveryURL> _returnListVal1SubscriptionSubscriptionFilterFindBusinessDiscoveryURLsDiscoveryURL = new java.util.ArrayList<org.uddi.api_v3.DiscoveryURL>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessDiscoveryURLs.getDiscoveryURL().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessDiscoveryURLsDiscoveryURL);
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setDiscoveryURLs(_returnListVal1SubscriptionSubscriptionFilterFindBusinessDiscoveryURLs);
            org.uddi.api_v3.FindRelatedBusinesses _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses = new org.uddi.api_v3.FindRelatedBusinesses();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses.setAuthInfo("AuthInfo-2143845847");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesFindQualifiers);
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses.setBusinessKey("BusinessKey997375824");
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses.setFromKey("FromKey-220616101");
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses.setToKey("ToKey236703547");
            org.uddi.api_v3.KeyedReference _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesKeyedReference = new org.uddi.api_v3.KeyedReference();
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesKeyedReference.setTModelKey("TModelKey1374776635");
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesKeyedReference.setKeyName("KeyName503867574");
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesKeyedReference.setKeyValue("KeyValue-1211058007");
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses.setKeyedReference(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinessesKeyedReference);
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses.setMaxRows(Integer.valueOf(-524468691));
            _returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses.setListHead(Integer.valueOf(-360149581));
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setFindRelatedBusinesses(_returnListVal1SubscriptionSubscriptionFilterFindBusinessFindRelatedBusinesses);
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setMaxRows(Integer.valueOf(106540917));
            _returnListVal1SubscriptionSubscriptionFilterFindBusiness.setListHead(Integer.valueOf(921182182));
            _returnListVal1SubscriptionSubscriptionFilter.setFindBusiness(_returnListVal1SubscriptionSubscriptionFilterFindBusiness);
            org.uddi.api_v3.FindRelatedBusinesses _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses = new org.uddi.api_v3.FindRelatedBusinesses();
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses.setAuthInfo("AuthInfo706596561");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesFindQualifiers);
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses.setBusinessKey("BusinessKey-433735275");
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses.setFromKey("FromKey-479161432");
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses.setToKey("ToKey-2017767956");
            org.uddi.api_v3.KeyedReference _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesKeyedReference = new org.uddi.api_v3.KeyedReference();
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesKeyedReference.setTModelKey("TModelKey-1499330517");
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesKeyedReference.setKeyName("KeyName-148962611");
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesKeyedReference.setKeyValue("KeyValue2046043958");
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses.setKeyedReference(_returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinessesKeyedReference);
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses.setMaxRows(Integer.valueOf(390225856));
            _returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses.setListHead(Integer.valueOf(-303766997));
            _returnListVal1SubscriptionSubscriptionFilter.setFindRelatedBusinesses(_returnListVal1SubscriptionSubscriptionFilterFindRelatedBusinesses);
            org.uddi.api_v3.FindService _returnListVal1SubscriptionSubscriptionFilterFindService = new org.uddi.api_v3.FindService();
            _returnListVal1SubscriptionSubscriptionFilterFindService.setAuthInfo("AuthInfo-1965161338");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindServiceFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindServiceFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindService.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindQualifiers);
            java.util.List<org.uddi.api_v3.Name> _returnListVal1SubscriptionSubscriptionFilterFindServiceName = new java.util.ArrayList<org.uddi.api_v3.Name>();
            _returnListVal1SubscriptionSubscriptionFilterFindService.getName().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceName);
            org.uddi.api_v3.CategoryBag _returnListVal1SubscriptionSubscriptionFilterFindServiceCategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindServiceCategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceCategoryBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceCategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnListVal1SubscriptionSubscriptionFilterFindServiceCategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceCategoryBag.getKeyedReferenceGroup().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceCategoryBagKeyedReferenceGroup);
            _returnListVal1SubscriptionSubscriptionFilterFindService.setCategoryBag(_returnListVal1SubscriptionSubscriptionFilterFindServiceCategoryBag);
            org.uddi.api_v3.TModelBag _returnListVal1SubscriptionSubscriptionFilterFindServiceTModelBag = new org.uddi.api_v3.TModelBag();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindServiceTModelBagTModelKey = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceTModelBag.getTModelKey().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceTModelBagTModelKey);
            _returnListVal1SubscriptionSubscriptionFilterFindService.setTModelBag(_returnListVal1SubscriptionSubscriptionFilterFindServiceTModelBag);
            org.uddi.api_v3.FindTModel _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel = new org.uddi.api_v3.FindTModel();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel.setAuthInfo("AuthInfo-1524567393");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelFindQualifiers);
            org.uddi.api_v3.Name _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelName = new org.uddi.api_v3.Name();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelName.setValue("Value1489838344");
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelName.setLang("Lang1711849999");
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel.setName(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelName);
            org.uddi.api_v3.IdentifierBag _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelIdentifierBag = new org.uddi.api_v3.IdentifierBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelIdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelIdentifierBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelIdentifierBagKeyedReference);
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel.setIdentifierBag(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelIdentifierBag);
            org.uddi.api_v3.CategoryBag _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelCategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelCategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelCategoryBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelCategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelCategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelCategoryBag.getKeyedReferenceGroup().addAll(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelCategoryBagKeyedReferenceGroup);
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel.setCategoryBag(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModelCategoryBag);
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel.setMaxRows(Integer.valueOf(-1974652484));
            _returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel.setListHead(Integer.valueOf(1113350648));
            _returnListVal1SubscriptionSubscriptionFilterFindService.setFindTModel(_returnListVal1SubscriptionSubscriptionFilterFindServiceFindTModel);
            _returnListVal1SubscriptionSubscriptionFilterFindService.setMaxRows(Integer.valueOf(2137657018));
            _returnListVal1SubscriptionSubscriptionFilterFindService.setBusinessKey("BusinessKey1458657542");
            _returnListVal1SubscriptionSubscriptionFilterFindService.setListHead(Integer.valueOf(-21825265));
            _returnListVal1SubscriptionSubscriptionFilter.setFindService(_returnListVal1SubscriptionSubscriptionFilterFindService);
            org.uddi.api_v3.FindTModel _returnListVal1SubscriptionSubscriptionFilterFindTModel = new org.uddi.api_v3.FindTModel();
            _returnListVal1SubscriptionSubscriptionFilterFindTModel.setAuthInfo("AuthInfo606305844");
            org.uddi.api_v3.FindQualifiers _returnListVal1SubscriptionSubscriptionFilterFindTModelFindQualifiers = new org.uddi.api_v3.FindQualifiers();
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterFindTModelFindQualifiersFindQualifier = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterFindTModelFindQualifiers.getFindQualifier().addAll(_returnListVal1SubscriptionSubscriptionFilterFindTModelFindQualifiersFindQualifier);
            _returnListVal1SubscriptionSubscriptionFilterFindTModel.setFindQualifiers(_returnListVal1SubscriptionSubscriptionFilterFindTModelFindQualifiers);
            org.uddi.api_v3.Name _returnListVal1SubscriptionSubscriptionFilterFindTModelName = new org.uddi.api_v3.Name();
            _returnListVal1SubscriptionSubscriptionFilterFindTModelName.setValue("Value716067094");
            _returnListVal1SubscriptionSubscriptionFilterFindTModelName.setLang("Lang719997205");
            _returnListVal1SubscriptionSubscriptionFilterFindTModel.setName(_returnListVal1SubscriptionSubscriptionFilterFindTModelName);
            org.uddi.api_v3.IdentifierBag _returnListVal1SubscriptionSubscriptionFilterFindTModelIdentifierBag = new org.uddi.api_v3.IdentifierBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindTModelIdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindTModelIdentifierBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindTModelIdentifierBagKeyedReference);
            _returnListVal1SubscriptionSubscriptionFilterFindTModel.setIdentifierBag(_returnListVal1SubscriptionSubscriptionFilterFindTModelIdentifierBag);
            org.uddi.api_v3.CategoryBag _returnListVal1SubscriptionSubscriptionFilterFindTModelCategoryBag = new org.uddi.api_v3.CategoryBag();
            java.util.List<org.uddi.api_v3.KeyedReference> _returnListVal1SubscriptionSubscriptionFilterFindTModelCategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
            _returnListVal1SubscriptionSubscriptionFilterFindTModelCategoryBag.getKeyedReference().addAll(_returnListVal1SubscriptionSubscriptionFilterFindTModelCategoryBagKeyedReference);
            java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _returnListVal1SubscriptionSubscriptionFilterFindTModelCategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
            _returnListVal1SubscriptionSubscriptionFilterFindTModelCategoryBag.getKeyedReferenceGroup().addAll(_returnListVal1SubscriptionSubscriptionFilterFindTModelCategoryBagKeyedReferenceGroup);
            _returnListVal1SubscriptionSubscriptionFilterFindTModel.setCategoryBag(_returnListVal1SubscriptionSubscriptionFilterFindTModelCategoryBag);
            _returnListVal1SubscriptionSubscriptionFilterFindTModel.setMaxRows(Integer.valueOf(184209882));
            _returnListVal1SubscriptionSubscriptionFilterFindTModel.setListHead(Integer.valueOf(1045788324));
            _returnListVal1SubscriptionSubscriptionFilter.setFindTModel(_returnListVal1SubscriptionSubscriptionFilterFindTModel);
            org.uddi.api_v3.GetBindingDetail _returnListVal1SubscriptionSubscriptionFilterGetBindingDetail = new org.uddi.api_v3.GetBindingDetail();
            _returnListVal1SubscriptionSubscriptionFilterGetBindingDetail.setAuthInfo("AuthInfo2007949525");
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterGetBindingDetailBindingKey = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterGetBindingDetail.getBindingKey().addAll(_returnListVal1SubscriptionSubscriptionFilterGetBindingDetailBindingKey);
            _returnListVal1SubscriptionSubscriptionFilter.setGetBindingDetail(_returnListVal1SubscriptionSubscriptionFilterGetBindingDetail);
            org.uddi.api_v3.GetBusinessDetail _returnListVal1SubscriptionSubscriptionFilterGetBusinessDetail = new org.uddi.api_v3.GetBusinessDetail();
            _returnListVal1SubscriptionSubscriptionFilterGetBusinessDetail.setAuthInfo("AuthInfo-468143042");
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterGetBusinessDetailBusinessKey = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterGetBusinessDetail.getBusinessKey().addAll(_returnListVal1SubscriptionSubscriptionFilterGetBusinessDetailBusinessKey);
            _returnListVal1SubscriptionSubscriptionFilter.setGetBusinessDetail(_returnListVal1SubscriptionSubscriptionFilterGetBusinessDetail);
            org.uddi.api_v3.GetServiceDetail _returnListVal1SubscriptionSubscriptionFilterGetServiceDetail = new org.uddi.api_v3.GetServiceDetail();
            _returnListVal1SubscriptionSubscriptionFilterGetServiceDetail.setAuthInfo("AuthInfo551126660");
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterGetServiceDetailServiceKey = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterGetServiceDetail.getServiceKey().addAll(_returnListVal1SubscriptionSubscriptionFilterGetServiceDetailServiceKey);
            _returnListVal1SubscriptionSubscriptionFilter.setGetServiceDetail(_returnListVal1SubscriptionSubscriptionFilterGetServiceDetail);
            org.uddi.api_v3.GetTModelDetail _returnListVal1SubscriptionSubscriptionFilterGetTModelDetail = new org.uddi.api_v3.GetTModelDetail();
            _returnListVal1SubscriptionSubscriptionFilterGetTModelDetail.setAuthInfo("AuthInfo1054785216");
            java.util.List<java.lang.String> _returnListVal1SubscriptionSubscriptionFilterGetTModelDetailTModelKey = new java.util.ArrayList<java.lang.String>();
            _returnListVal1SubscriptionSubscriptionFilterGetTModelDetail.getTModelKey().addAll(_returnListVal1SubscriptionSubscriptionFilterGetTModelDetailTModelKey);
            _returnListVal1SubscriptionSubscriptionFilter.setGetTModelDetail(_returnListVal1SubscriptionSubscriptionFilterGetTModelDetail);
            org.uddi.api_v3.GetAssertionStatusReport _returnListVal1SubscriptionSubscriptionFilterGetAssertionStatusReport = new org.uddi.api_v3.GetAssertionStatusReport();
            _returnListVal1SubscriptionSubscriptionFilterGetAssertionStatusReport.setAuthInfo("AuthInfo659180450");
            org.uddi.api_v3.CompletionStatus _returnListVal1SubscriptionSubscriptionFilterGetAssertionStatusReportCompletionStatus = org.uddi.api_v3.CompletionStatus.STATUS_FROM_KEY_INCOMPLETE;
            _returnListVal1SubscriptionSubscriptionFilterGetAssertionStatusReport.setCompletionStatus(_returnListVal1SubscriptionSubscriptionFilterGetAssertionStatusReportCompletionStatus);
            _returnListVal1SubscriptionSubscriptionFilter.setGetAssertionStatusReport(_returnListVal1SubscriptionSubscriptionFilterGetAssertionStatusReport);
            _returnListVal1Subscription.setSubscriptionFilter(_returnListVal1SubscriptionSubscriptionFilter);
            _returnListVal1Subscription.setBindingKey("BindingKey-767864811");
            _returnListVal1Subscription.setNotificationInterval(javax.xml.datatype.DatatypeFactory.newInstance().newDuration("P243912939Y0M30DT19H44M0.969S"));
            _returnListVal1Subscription.setMaxEntities(Integer.valueOf(535111254));
            java.lang.Object _returnListVal1SubscriptionExpiresAfter = null;
            _returnListVal1Subscription.setExpiresAfter(_returnListVal1SubscriptionExpiresAfter);
            _returnListVal1Subscription.setBrief(Boolean.valueOf(false));
            _returnListVal1.setSubscription(_returnListVal1Subscription);
            org.uddi.api_v3.BindingDetail _returnListVal1BindingDetail = new org.uddi.api_v3.BindingDetail();
            org.uddi.api_v3.ListDescription _returnListVal1BindingDetailListDescription = new org.uddi.api_v3.ListDescription();
            _returnListVal1BindingDetailListDescription.setIncludeCount(-1656323868);
            _returnListVal1BindingDetailListDescription.setActualCount(465020718);
            _returnListVal1BindingDetailListDescription.setListHead(376396014);
            _returnListVal1BindingDetail.setListDescription(_returnListVal1BindingDetailListDescription);
            java.util.List<org.uddi.api_v3.BindingTemplate> _returnListVal1BindingDetailBindingTemplate = new java.util.ArrayList<org.uddi.api_v3.BindingTemplate>();
            _returnListVal1BindingDetail.getBindingTemplate().addAll(_returnListVal1BindingDetailBindingTemplate);
            _returnListVal1BindingDetail.setTruncated(Boolean.valueOf(true));
            _returnListVal1.setBindingDetail(_returnListVal1BindingDetail);
            org.uddi.api_v3.BusinessDetail _returnListVal1BusinessDetail = new org.uddi.api_v3.BusinessDetail();
            java.util.List<org.uddi.api_v3.BusinessEntity> _returnListVal1BusinessDetailBusinessEntity = new java.util.ArrayList<org.uddi.api_v3.BusinessEntity>();
            _returnListVal1BusinessDetail.getBusinessEntity().addAll(_returnListVal1BusinessDetailBusinessEntity);
            _returnListVal1BusinessDetail.setTruncated(Boolean.valueOf(true));
            _returnListVal1.setBusinessDetail(_returnListVal1BusinessDetail);
            org.uddi.api_v3.ServiceDetail _returnListVal1ServiceDetail = new org.uddi.api_v3.ServiceDetail();
            java.util.List<org.uddi.api_v3.BusinessService> _returnListVal1ServiceDetailBusinessService = new java.util.ArrayList<org.uddi.api_v3.BusinessService>();
            _returnListVal1ServiceDetail.getBusinessService().addAll(_returnListVal1ServiceDetailBusinessService);
            _returnListVal1ServiceDetail.setTruncated(Boolean.valueOf(false));
            _returnListVal1.setServiceDetail(_returnListVal1ServiceDetail);
            org.uddi.api_v3.TModelDetail _returnListVal1TModelDetail = new org.uddi.api_v3.TModelDetail();
            java.util.List<org.uddi.api_v3.TModel> _returnListVal1TModelDetailTModel = new java.util.ArrayList<org.uddi.api_v3.TModel>();
            _returnListVal1TModelDetail.getTModel().addAll(_returnListVal1TModelDetailTModel);
            _returnListVal1TModelDetail.setTruncated(Boolean.valueOf(true));
            _returnListVal1.setTModelDetail(_returnListVal1TModelDetail);
            org.uddi.api_v3.BusinessList _returnListVal1BusinessList = new org.uddi.api_v3.BusinessList();
            org.uddi.api_v3.ListDescription _returnListVal1BusinessListListDescription = new org.uddi.api_v3.ListDescription();
            _returnListVal1BusinessListListDescription.setIncludeCount(504960546);
            _returnListVal1BusinessListListDescription.setActualCount(-1178691070);
            _returnListVal1BusinessListListDescription.setListHead(592498093);
            _returnListVal1BusinessList.setListDescription(_returnListVal1BusinessListListDescription);
            org.uddi.api_v3.BusinessInfos _returnListVal1BusinessListBusinessInfos = new org.uddi.api_v3.BusinessInfos();
            java.util.List<org.uddi.api_v3.BusinessInfo> _returnListVal1BusinessListBusinessInfosBusinessInfo = new java.util.ArrayList<org.uddi.api_v3.BusinessInfo>();
            _returnListVal1BusinessListBusinessInfos.getBusinessInfo().addAll(_returnListVal1BusinessListBusinessInfosBusinessInfo);
            _returnListVal1BusinessList.setBusinessInfos(_returnListVal1BusinessListBusinessInfos);
            _returnListVal1BusinessList.setTruncated(Boolean.valueOf(false));
            _returnListVal1.setBusinessList(_returnListVal1BusinessList);
            org.uddi.api_v3.RelatedBusinessesList _returnListVal1RelatedBusinessesList = new org.uddi.api_v3.RelatedBusinessesList();
            org.uddi.api_v3.ListDescription _returnListVal1RelatedBusinessesListListDescription = new org.uddi.api_v3.ListDescription();
            _returnListVal1RelatedBusinessesListListDescription.setIncludeCount(1401695612);
            _returnListVal1RelatedBusinessesListListDescription.setActualCount(219801722);
            _returnListVal1RelatedBusinessesListListDescription.setListHead(-613946729);
            _returnListVal1RelatedBusinessesList.setListDescription(_returnListVal1RelatedBusinessesListListDescription);
            _returnListVal1RelatedBusinessesList.setBusinessKey("BusinessKey1132037220");
            org.uddi.api_v3.RelatedBusinessInfos _returnListVal1RelatedBusinessesListRelatedBusinessInfos = new org.uddi.api_v3.RelatedBusinessInfos();
            java.util.List<org.uddi.api_v3.RelatedBusinessInfo> _returnListVal1RelatedBusinessesListRelatedBusinessInfosRelatedBusinessInfo = new java.util.ArrayList<org.uddi.api_v3.RelatedBusinessInfo>();
            _returnListVal1RelatedBusinessesListRelatedBusinessInfos.getRelatedBusinessInfo().addAll(_returnListVal1RelatedBusinessesListRelatedBusinessInfosRelatedBusinessInfo);
            _returnListVal1RelatedBusinessesList.setRelatedBusinessInfos(_returnListVal1RelatedBusinessesListRelatedBusinessInfos);
            _returnListVal1RelatedBusinessesList.setTruncated(Boolean.valueOf(true));
            _returnListVal1.setRelatedBusinessesList(_returnListVal1RelatedBusinessesList);
            org.uddi.api_v3.ServiceList _returnListVal1ServiceList = new org.uddi.api_v3.ServiceList();
            org.uddi.api_v3.ListDescription _returnListVal1ServiceListListDescription = new org.uddi.api_v3.ListDescription();
            _returnListVal1ServiceListListDescription.setIncludeCount(-991839039);
            _returnListVal1ServiceListListDescription.setActualCount(742881032);
            _returnListVal1ServiceListListDescription.setListHead(-617537948);
            _returnListVal1ServiceList.setListDescription(_returnListVal1ServiceListListDescription);
            org.uddi.api_v3.ServiceInfos _returnListVal1ServiceListServiceInfos = new org.uddi.api_v3.ServiceInfos();
            java.util.List<org.uddi.api_v3.ServiceInfo> _returnListVal1ServiceListServiceInfosServiceInfo = new java.util.ArrayList<org.uddi.api_v3.ServiceInfo>();
            _returnListVal1ServiceListServiceInfos.getServiceInfo().addAll(_returnListVal1ServiceListServiceInfosServiceInfo);
            _returnListVal1ServiceList.setServiceInfos(_returnListVal1ServiceListServiceInfos);
            _returnListVal1ServiceList.setTruncated(Boolean.valueOf(true));
            _returnListVal1.setServiceList(_returnListVal1ServiceList);
            org.uddi.api_v3.TModelList _returnListVal1TModelList = new org.uddi.api_v3.TModelList();
            org.uddi.api_v3.ListDescription _returnListVal1TModelListListDescription = new org.uddi.api_v3.ListDescription();
            _returnListVal1TModelListListDescription.setIncludeCount(936089017);
            _returnListVal1TModelListListDescription.setActualCount(-900106013);
            _returnListVal1TModelListListDescription.setListHead(1178513937);
            _returnListVal1TModelList.setListDescription(_returnListVal1TModelListListDescription);
            org.uddi.api_v3.TModelInfos _returnListVal1TModelListTModelInfos = new org.uddi.api_v3.TModelInfos();
            java.util.List<org.uddi.api_v3.TModelInfo> _returnListVal1TModelListTModelInfosTModelInfo = new java.util.ArrayList<org.uddi.api_v3.TModelInfo>();
            _returnListVal1TModelListTModelInfos.getTModelInfo().addAll(_returnListVal1TModelListTModelInfosTModelInfo);
            _returnListVal1TModelList.setTModelInfos(_returnListVal1TModelListTModelInfos);
            _returnListVal1TModelList.setTruncated(Boolean.valueOf(false));
            _returnListVal1.setTModelList(_returnListVal1TModelList);
            org.uddi.api_v3.AssertionStatusReport _returnListVal1AssertionStatusReport = new org.uddi.api_v3.AssertionStatusReport();
            java.util.List<org.uddi.api_v3.AssertionStatusItem> _returnListVal1AssertionStatusReportAssertionStatusItem = new java.util.ArrayList<org.uddi.api_v3.AssertionStatusItem>();
            _returnListVal1AssertionStatusReport.getAssertionStatusItem().addAll(_returnListVal1AssertionStatusReportAssertionStatusItem);
            _returnListVal1.setAssertionStatusReport(_returnListVal1AssertionStatusReport);
            java.util.List<org.uddi.sub_v3.KeyBag> _returnListVal1KeyBag = new java.util.ArrayList<org.uddi.sub_v3.KeyBag>();
            _returnListVal1.getKeyBag().addAll(_returnListVal1KeyBag);
            _returnListVal1.setSomeResultsUnavailable(Boolean.valueOf(true));
            _returnList.add(_returnListVal1);
            _return.getList().addAll(_returnList);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
