
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.uddi.v3_service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-04-05T12:42:24.247+02:00
 * Generated source version: 3.0.0-milestone1
 * 
 */

@javax.jws.WebService(
                      serviceName = "UDDISecurityService",
                      portName = "UDDISecurityImplPort",
                      targetNamespace = "urn:uddi-org:v3_service",
                      wsdlLocation = "http://localhost:8081/juddiv3/services/security?wsdl",
                      endpointInterface = "org.uddi.v3_service.UDDISecurityPortType")
                      
public class UDDISecurityPortTypeImpl implements UDDISecurityPortType {

    private static final Logger LOG = Logger.getLogger(UDDISecurityPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDISecurityPortType#discardAuthToken(org.uddi.api_v3.DiscardAuthToken  body )*
     */
    public void discardAuthToken(org.uddi.api_v3.DiscardAuthToken body) { 
        LOG.info("Executing operation discardAuthToken");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.uddi.v3_service.UDDISecurityPortType#getAuthToken(org.uddi.api_v3.GetAuthToken  body )*
     */
    public org.uddi.api_v3.AuthToken getAuthToken(org.uddi.api_v3.GetAuthToken body) { 
        LOG.info("Executing operation getAuthToken");
        System.out.println(body);
        try {
            org.uddi.api_v3.AuthToken _return = new org.uddi.api_v3.AuthToken();
            _return.setAuthInfo("AuthInfo1681564486");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
