
package org.uddi.v3_service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-07T20:14:04.688+01:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
public final class UDDIPublicationPortType_UDDIPublicationImplPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:uddi-org:v3_service", "UDDIPublicationService");

    private UDDIPublicationPortType_UDDIPublicationImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UDDIPublicationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UDDIPublicationService ss = new UDDIPublicationService(wsdlURL, SERVICE_NAME);
        UDDIPublicationPortType port = ss.getUDDIPublicationImplPort();  
        
        {
        System.out.println("Invoking deleteBusiness...");
        org.uddi.api_v3.DeleteBusiness _deleteBusiness_body = new org.uddi.api_v3.DeleteBusiness();
        _deleteBusiness_body.setAuthInfo("AuthInfo1956160655");
        java.util.List<java.lang.String> _deleteBusiness_bodyBusinessKey = new java.util.ArrayList<java.lang.String>();
        java.lang.String _deleteBusiness_bodyBusinessKeyVal1 = "_deleteBusiness_bodyBusinessKeyVal-1724722252";
        _deleteBusiness_bodyBusinessKey.add(_deleteBusiness_bodyBusinessKeyVal1);
        _deleteBusiness_body.getBusinessKey().addAll(_deleteBusiness_bodyBusinessKey);
        port.deleteBusiness(_deleteBusiness_body);


        }
        {
        System.out.println("Invoking deleteService...");
        org.uddi.api_v3.DeleteService _deleteService_body = new org.uddi.api_v3.DeleteService();
        _deleteService_body.setAuthInfo("AuthInfo-1865271607");
        java.util.List<java.lang.String> _deleteService_bodyServiceKey = new java.util.ArrayList<java.lang.String>();
        java.lang.String _deleteService_bodyServiceKeyVal1 = "_deleteService_bodyServiceKeyVal-1884172381";
        _deleteService_bodyServiceKey.add(_deleteService_bodyServiceKeyVal1);
        _deleteService_body.getServiceKey().addAll(_deleteService_bodyServiceKey);
        port.deleteService(_deleteService_body);


        }
        {
        System.out.println("Invoking saveService...");
        org.uddi.api_v3.SaveService _saveService_body = new org.uddi.api_v3.SaveService();
        _saveService_body.setAuthInfo("AuthInfo-708335198");
        java.util.List<org.uddi.api_v3.BusinessService> _saveService_bodyBusinessService = new java.util.ArrayList<org.uddi.api_v3.BusinessService>();
        org.uddi.api_v3.BusinessService _saveService_bodyBusinessServiceVal1 = new org.uddi.api_v3.BusinessService();
        java.util.List<org.uddi.api_v3.Name> _saveService_bodyBusinessServiceVal1Name = new java.util.ArrayList<org.uddi.api_v3.Name>();
        _saveService_bodyBusinessServiceVal1.getName().addAll(_saveService_bodyBusinessServiceVal1Name);
        java.util.List<org.uddi.api_v3.Description> _saveService_bodyBusinessServiceVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
        _saveService_bodyBusinessServiceVal1.getDescription().addAll(_saveService_bodyBusinessServiceVal1Description);
        org.uddi.api_v3.BindingTemplates _saveService_bodyBusinessServiceVal1BindingTemplates = new org.uddi.api_v3.BindingTemplates();
        java.util.List<org.uddi.api_v3.BindingTemplate> _saveService_bodyBusinessServiceVal1BindingTemplatesBindingTemplate = new java.util.ArrayList<org.uddi.api_v3.BindingTemplate>();
        _saveService_bodyBusinessServiceVal1BindingTemplates.getBindingTemplate().addAll(_saveService_bodyBusinessServiceVal1BindingTemplatesBindingTemplate);
        _saveService_bodyBusinessServiceVal1.setBindingTemplates(_saveService_bodyBusinessServiceVal1BindingTemplates);
        org.uddi.api_v3.CategoryBag _saveService_bodyBusinessServiceVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
        java.util.List<org.uddi.api_v3.KeyedReference> _saveService_bodyBusinessServiceVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
        _saveService_bodyBusinessServiceVal1CategoryBag.getKeyedReference().addAll(_saveService_bodyBusinessServiceVal1CategoryBagKeyedReference);
        java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _saveService_bodyBusinessServiceVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
        _saveService_bodyBusinessServiceVal1CategoryBag.getKeyedReferenceGroup().addAll(_saveService_bodyBusinessServiceVal1CategoryBagKeyedReferenceGroup);
        _saveService_bodyBusinessServiceVal1.setCategoryBag(_saveService_bodyBusinessServiceVal1CategoryBag);
        java.util.List<org.w3._2000._09.xmldsig.SignatureType> _saveService_bodyBusinessServiceVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
        _saveService_bodyBusinessServiceVal1.getSignature().addAll(_saveService_bodyBusinessServiceVal1Signature);
        _saveService_bodyBusinessServiceVal1.setServiceKey("ServiceKey1673952259");
        _saveService_bodyBusinessServiceVal1.setBusinessKey("BusinessKey-834764238");
        _saveService_bodyBusinessService.add(_saveService_bodyBusinessServiceVal1);
        _saveService_body.getBusinessService().addAll(_saveService_bodyBusinessService);
        org.uddi.api_v3.ServiceDetail _saveService__return = port.saveService(_saveService_body);
        System.out.println("saveService.result=" + _saveService__return);


        }
        {
        System.out.println("Invoking setPublisherAssertions...");
        java.lang.String _setPublisherAssertions_authInfo = "_setPublisherAssertions_authInfo992887477";
        java.util.List<org.uddi.api_v3.PublisherAssertion> _setPublisherAssertions_publisherAssertionVal = new java.util.ArrayList<org.uddi.api_v3.PublisherAssertion>();
        org.uddi.api_v3.PublisherAssertion _setPublisherAssertions_publisherAssertionValVal1 = new org.uddi.api_v3.PublisherAssertion();
        _setPublisherAssertions_publisherAssertionValVal1.setFromKey("FromKey858930835");
        _setPublisherAssertions_publisherAssertionValVal1.setToKey("ToKey-667508773");
        org.uddi.api_v3.KeyedReference _setPublisherAssertions_publisherAssertionValVal1KeyedReference = new org.uddi.api_v3.KeyedReference();
        _setPublisherAssertions_publisherAssertionValVal1KeyedReference.setTModelKey("TModelKey-1092809305");
        _setPublisherAssertions_publisherAssertionValVal1KeyedReference.setKeyName("KeyName880701110");
        _setPublisherAssertions_publisherAssertionValVal1KeyedReference.setKeyValue("KeyValue-250288283");
        _setPublisherAssertions_publisherAssertionValVal1.setKeyedReference(_setPublisherAssertions_publisherAssertionValVal1KeyedReference);
        java.util.List<org.w3._2000._09.xmldsig.SignatureType> _setPublisherAssertions_publisherAssertionValVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
        org.w3._2000._09.xmldsig.SignatureType _setPublisherAssertions_publisherAssertionValVal1SignatureVal1 = new org.w3._2000._09.xmldsig.SignatureType();
        org.w3._2000._09.xmldsig.SignedInfoType _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfo = new org.w3._2000._09.xmldsig.SignedInfoType();
        org.w3._2000._09.xmldsig.CanonicalizationMethodType _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoCanonicalizationMethod = new org.w3._2000._09.xmldsig.CanonicalizationMethodType();
        java.util.List<java.lang.Object> _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoCanonicalizationMethodContent = new java.util.ArrayList<java.lang.Object>();
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoCanonicalizationMethod.getContent().addAll(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoCanonicalizationMethodContent);
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoCanonicalizationMethod.setAlgorithm("Algorithm2007721701");
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfo.setCanonicalizationMethod(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoCanonicalizationMethod);
        org.w3._2000._09.xmldsig.SignatureMethodType _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoSignatureMethod = new org.w3._2000._09.xmldsig.SignatureMethodType();
        java.util.List<java.lang.Object> _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoSignatureMethodContent = new java.util.ArrayList<java.lang.Object>();
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoSignatureMethod.getContent().addAll(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoSignatureMethodContent);
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoSignatureMethod.setAlgorithm("Algorithm-1570138280");
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfo.setSignatureMethod(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoSignatureMethod);
        java.util.List<org.w3._2000._09.xmldsig.ReferenceType> _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoReference = new java.util.ArrayList<org.w3._2000._09.xmldsig.ReferenceType>();
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfo.getReference().addAll(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfoReference);
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfo.setId("Id319471228");
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1.setSignedInfo(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignedInfo);
        org.w3._2000._09.xmldsig.SignatureValueType _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignatureValue = new org.w3._2000._09.xmldsig.SignatureValueType();
        byte[] _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignatureValueValue = new byte[] {};
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignatureValue.setValue(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignatureValueValue);
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignatureValue.setId("Id876349244");
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1.setSignatureValue(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1SignatureValue);
        org.w3._2000._09.xmldsig.KeyInfoType _setPublisherAssertions_publisherAssertionValVal1SignatureVal1KeyInfo = new org.w3._2000._09.xmldsig.KeyInfoType();
        java.util.List<java.lang.Object> _setPublisherAssertions_publisherAssertionValVal1SignatureVal1KeyInfoContent = new java.util.ArrayList<java.lang.Object>();
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1KeyInfo.getContent().addAll(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1KeyInfoContent);
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1KeyInfo.setId("Id1744080060");
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1.setKeyInfo(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1KeyInfo);
        java.util.List<org.w3._2000._09.xmldsig.ObjectType> _setPublisherAssertions_publisherAssertionValVal1SignatureVal1Object = new java.util.ArrayList<org.w3._2000._09.xmldsig.ObjectType>();
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1.getObject().addAll(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1Object);
        _setPublisherAssertions_publisherAssertionValVal1SignatureVal1.setId("Id2096221651");
        _setPublisherAssertions_publisherAssertionValVal1Signature.add(_setPublisherAssertions_publisherAssertionValVal1SignatureVal1);
        _setPublisherAssertions_publisherAssertionValVal1.getSignature().addAll(_setPublisherAssertions_publisherAssertionValVal1Signature);
        _setPublisherAssertions_publisherAssertionVal.add(_setPublisherAssertions_publisherAssertionValVal1);
        javax.xml.ws.Holder<java.util.List<org.uddi.api_v3.PublisherAssertion>> _setPublisherAssertions_publisherAssertion = new javax.xml.ws.Holder<java.util.List<org.uddi.api_v3.PublisherAssertion>>(_setPublisherAssertions_publisherAssertionVal);
        port.setPublisherAssertions(_setPublisherAssertions_authInfo, _setPublisherAssertions_publisherAssertion);

        System.out.println("setPublisherAssertions._setPublisherAssertions_publisherAssertion=" + _setPublisherAssertions_publisherAssertion.value);

        }
        {
        System.out.println("Invoking deleteBinding...");
        org.uddi.api_v3.DeleteBinding _deleteBinding_body = new org.uddi.api_v3.DeleteBinding();
        _deleteBinding_body.setAuthInfo("AuthInfo896967296");
        java.util.List<java.lang.String> _deleteBinding_bodyBindingKey = new java.util.ArrayList<java.lang.String>();
        java.lang.String _deleteBinding_bodyBindingKeyVal1 = "_deleteBinding_bodyBindingKeyVal1120618090";
        _deleteBinding_bodyBindingKey.add(_deleteBinding_bodyBindingKeyVal1);
        _deleteBinding_body.getBindingKey().addAll(_deleteBinding_bodyBindingKey);
        port.deleteBinding(_deleteBinding_body);


        }
        {
        System.out.println("Invoking getPublisherAssertions...");
        java.lang.String _getPublisherAssertions_authInfo = "_getPublisherAssertions_authInfo1372022939";
        java.util.List<org.uddi.api_v3.PublisherAssertion> _getPublisherAssertions__return = port.getPublisherAssertions(_getPublisherAssertions_authInfo);
        System.out.println("getPublisherAssertions.result=" + _getPublisherAssertions__return);


        }
        {
        System.out.println("Invoking deletePublisherAssertions...");
        org.uddi.api_v3.DeletePublisherAssertions _deletePublisherAssertions_body = new org.uddi.api_v3.DeletePublisherAssertions();
        _deletePublisherAssertions_body.setAuthInfo("AuthInfo-1541779542");
        java.util.List<org.uddi.api_v3.PublisherAssertion> _deletePublisherAssertions_bodyPublisherAssertion = new java.util.ArrayList<org.uddi.api_v3.PublisherAssertion>();
        org.uddi.api_v3.PublisherAssertion _deletePublisherAssertions_bodyPublisherAssertionVal1 = new org.uddi.api_v3.PublisherAssertion();
        _deletePublisherAssertions_bodyPublisherAssertionVal1.setFromKey("FromKey-924925519");
        _deletePublisherAssertions_bodyPublisherAssertionVal1.setToKey("ToKey1426511016");
        org.uddi.api_v3.KeyedReference _deletePublisherAssertions_bodyPublisherAssertionVal1KeyedReference = new org.uddi.api_v3.KeyedReference();
        _deletePublisherAssertions_bodyPublisherAssertionVal1KeyedReference.setTModelKey("TModelKey648625240");
        _deletePublisherAssertions_bodyPublisherAssertionVal1KeyedReference.setKeyName("KeyName-406748846");
        _deletePublisherAssertions_bodyPublisherAssertionVal1KeyedReference.setKeyValue("KeyValue1216930694");
        _deletePublisherAssertions_bodyPublisherAssertionVal1.setKeyedReference(_deletePublisherAssertions_bodyPublisherAssertionVal1KeyedReference);
        java.util.List<org.w3._2000._09.xmldsig.SignatureType> _deletePublisherAssertions_bodyPublisherAssertionVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
        _deletePublisherAssertions_bodyPublisherAssertionVal1.getSignature().addAll(_deletePublisherAssertions_bodyPublisherAssertionVal1Signature);
        _deletePublisherAssertions_bodyPublisherAssertion.add(_deletePublisherAssertions_bodyPublisherAssertionVal1);
        _deletePublisherAssertions_body.getPublisherAssertion().addAll(_deletePublisherAssertions_bodyPublisherAssertion);
        port.deletePublisherAssertions(_deletePublisherAssertions_body);


        }
        {
        System.out.println("Invoking addPublisherAssertions...");
        org.uddi.api_v3.AddPublisherAssertions _addPublisherAssertions_body = new org.uddi.api_v3.AddPublisherAssertions();
        _addPublisherAssertions_body.setAuthInfo("AuthInfo569904035");
        java.util.List<org.uddi.api_v3.PublisherAssertion> _addPublisherAssertions_bodyPublisherAssertion = new java.util.ArrayList<org.uddi.api_v3.PublisherAssertion>();
        org.uddi.api_v3.PublisherAssertion _addPublisherAssertions_bodyPublisherAssertionVal1 = new org.uddi.api_v3.PublisherAssertion();
        _addPublisherAssertions_bodyPublisherAssertionVal1.setFromKey("FromKey918224529");
        _addPublisherAssertions_bodyPublisherAssertionVal1.setToKey("ToKey1902075214");
        org.uddi.api_v3.KeyedReference _addPublisherAssertions_bodyPublisherAssertionVal1KeyedReference = new org.uddi.api_v3.KeyedReference();
        _addPublisherAssertions_bodyPublisherAssertionVal1KeyedReference.setTModelKey("TModelKey-941627567");
        _addPublisherAssertions_bodyPublisherAssertionVal1KeyedReference.setKeyName("KeyName-1722075718");
        _addPublisherAssertions_bodyPublisherAssertionVal1KeyedReference.setKeyValue("KeyValue809178148");
        _addPublisherAssertions_bodyPublisherAssertionVal1.setKeyedReference(_addPublisherAssertions_bodyPublisherAssertionVal1KeyedReference);
        java.util.List<org.w3._2000._09.xmldsig.SignatureType> _addPublisherAssertions_bodyPublisherAssertionVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
        _addPublisherAssertions_bodyPublisherAssertionVal1.getSignature().addAll(_addPublisherAssertions_bodyPublisherAssertionVal1Signature);
        _addPublisherAssertions_bodyPublisherAssertion.add(_addPublisherAssertions_bodyPublisherAssertionVal1);
        _addPublisherAssertions_body.getPublisherAssertion().addAll(_addPublisherAssertions_bodyPublisherAssertion);
        port.addPublisherAssertions(_addPublisherAssertions_body);


        }
        {
        System.out.println("Invoking saveTModel...");
        org.uddi.api_v3.SaveTModel _saveTModel_body = new org.uddi.api_v3.SaveTModel();
        _saveTModel_body.setAuthInfo("AuthInfo-1446010229");
        java.util.List<org.uddi.api_v3.TModel> _saveTModel_bodyTModel = new java.util.ArrayList<org.uddi.api_v3.TModel>();
        org.uddi.api_v3.TModel _saveTModel_bodyTModelVal1 = new org.uddi.api_v3.TModel();
        org.uddi.api_v3.Name _saveTModel_bodyTModelVal1Name = new org.uddi.api_v3.Name();
        _saveTModel_bodyTModelVal1Name.setValue("Value-345547557");
        _saveTModel_bodyTModelVal1Name.setLang("Lang-1092846330");
        _saveTModel_bodyTModelVal1.setName(_saveTModel_bodyTModelVal1Name);
        java.util.List<org.uddi.api_v3.Description> _saveTModel_bodyTModelVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
        _saveTModel_bodyTModelVal1.getDescription().addAll(_saveTModel_bodyTModelVal1Description);
        java.util.List<org.uddi.api_v3.OverviewDoc> _saveTModel_bodyTModelVal1OverviewDoc = new java.util.ArrayList<org.uddi.api_v3.OverviewDoc>();
        _saveTModel_bodyTModelVal1.getOverviewDoc().addAll(_saveTModel_bodyTModelVal1OverviewDoc);
        org.uddi.api_v3.IdentifierBag _saveTModel_bodyTModelVal1IdentifierBag = new org.uddi.api_v3.IdentifierBag();
        java.util.List<org.uddi.api_v3.KeyedReference> _saveTModel_bodyTModelVal1IdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
        _saveTModel_bodyTModelVal1IdentifierBag.getKeyedReference().addAll(_saveTModel_bodyTModelVal1IdentifierBagKeyedReference);
        _saveTModel_bodyTModelVal1.setIdentifierBag(_saveTModel_bodyTModelVal1IdentifierBag);
        org.uddi.api_v3.CategoryBag _saveTModel_bodyTModelVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
        java.util.List<org.uddi.api_v3.KeyedReference> _saveTModel_bodyTModelVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
        _saveTModel_bodyTModelVal1CategoryBag.getKeyedReference().addAll(_saveTModel_bodyTModelVal1CategoryBagKeyedReference);
        java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _saveTModel_bodyTModelVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
        _saveTModel_bodyTModelVal1CategoryBag.getKeyedReferenceGroup().addAll(_saveTModel_bodyTModelVal1CategoryBagKeyedReferenceGroup);
        _saveTModel_bodyTModelVal1.setCategoryBag(_saveTModel_bodyTModelVal1CategoryBag);
        java.util.List<org.w3._2000._09.xmldsig.SignatureType> _saveTModel_bodyTModelVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
        _saveTModel_bodyTModelVal1.getSignature().addAll(_saveTModel_bodyTModelVal1Signature);
        _saveTModel_bodyTModelVal1.setTModelKey("TModelKey115649764");
        _saveTModel_bodyTModelVal1.setDeleted(Boolean.valueOf(true));
        _saveTModel_bodyTModel.add(_saveTModel_bodyTModelVal1);
        _saveTModel_body.getTModel().addAll(_saveTModel_bodyTModel);
        org.uddi.api_v3.TModelDetail _saveTModel__return = port.saveTModel(_saveTModel_body);
        System.out.println("saveTModel.result=" + _saveTModel__return);


        }
        {
        System.out.println("Invoking getAssertionStatusReport...");
        java.lang.String _getAssertionStatusReport_authInfo = "_getAssertionStatusReport_authInfo-604532180";
        org.uddi.api_v3.CompletionStatus _getAssertionStatusReport_completionStatus = org.uddi.api_v3.CompletionStatus.STATUS_BOTH_INCOMPLETE;
        java.util.List<org.uddi.api_v3.AssertionStatusItem> _getAssertionStatusReport__return = port.getAssertionStatusReport(_getAssertionStatusReport_authInfo, _getAssertionStatusReport_completionStatus);
        System.out.println("getAssertionStatusReport.result=" + _getAssertionStatusReport__return);


        }
        {
        System.out.println("Invoking deleteTModel...");
        org.uddi.api_v3.DeleteTModel _deleteTModel_body = new org.uddi.api_v3.DeleteTModel();
        _deleteTModel_body.setAuthInfo("AuthInfo1335605128");
        java.util.List<java.lang.String> _deleteTModel_bodyTModelKey = new java.util.ArrayList<java.lang.String>();
        java.lang.String _deleteTModel_bodyTModelKeyVal1 = "_deleteTModel_bodyTModelKeyVal-1006484276";
        _deleteTModel_bodyTModelKey.add(_deleteTModel_bodyTModelKeyVal1);
        _deleteTModel_body.getTModelKey().addAll(_deleteTModel_bodyTModelKey);
        port.deleteTModel(_deleteTModel_body);


        }
        {
        System.out.println("Invoking saveBusiness...");
        org.uddi.api_v3.SaveBusiness _saveBusiness_body = new org.uddi.api_v3.SaveBusiness();
        _saveBusiness_body.setAuthInfo("AuthInfo-1555289431");
        java.util.List<org.uddi.api_v3.BusinessEntity> _saveBusiness_bodyBusinessEntity = new java.util.ArrayList<org.uddi.api_v3.BusinessEntity>();
        org.uddi.api_v3.BusinessEntity _saveBusiness_bodyBusinessEntityVal1 = new org.uddi.api_v3.BusinessEntity();
        org.uddi.api_v3.DiscoveryURLs _saveBusiness_bodyBusinessEntityVal1DiscoveryURLs = new org.uddi.api_v3.DiscoveryURLs();
        java.util.List<org.uddi.api_v3.DiscoveryURL> _saveBusiness_bodyBusinessEntityVal1DiscoveryURLsDiscoveryURL = new java.util.ArrayList<org.uddi.api_v3.DiscoveryURL>();
        _saveBusiness_bodyBusinessEntityVal1DiscoveryURLs.getDiscoveryURL().addAll(_saveBusiness_bodyBusinessEntityVal1DiscoveryURLsDiscoveryURL);
        _saveBusiness_bodyBusinessEntityVal1.setDiscoveryURLs(_saveBusiness_bodyBusinessEntityVal1DiscoveryURLs);
        java.util.List<org.uddi.api_v3.Name> _saveBusiness_bodyBusinessEntityVal1Name = new java.util.ArrayList<org.uddi.api_v3.Name>();
        _saveBusiness_bodyBusinessEntityVal1.getName().addAll(_saveBusiness_bodyBusinessEntityVal1Name);
        java.util.List<org.uddi.api_v3.Description> _saveBusiness_bodyBusinessEntityVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
        _saveBusiness_bodyBusinessEntityVal1.getDescription().addAll(_saveBusiness_bodyBusinessEntityVal1Description);
        org.uddi.api_v3.Contacts _saveBusiness_bodyBusinessEntityVal1Contacts = new org.uddi.api_v3.Contacts();
        java.util.List<org.uddi.api_v3.Contact> _saveBusiness_bodyBusinessEntityVal1ContactsContact = new java.util.ArrayList<org.uddi.api_v3.Contact>();
        _saveBusiness_bodyBusinessEntityVal1Contacts.getContact().addAll(_saveBusiness_bodyBusinessEntityVal1ContactsContact);
        _saveBusiness_bodyBusinessEntityVal1.setContacts(_saveBusiness_bodyBusinessEntityVal1Contacts);
        org.uddi.api_v3.BusinessServices _saveBusiness_bodyBusinessEntityVal1BusinessServices = new org.uddi.api_v3.BusinessServices();
        java.util.List<org.uddi.api_v3.BusinessService> _saveBusiness_bodyBusinessEntityVal1BusinessServicesBusinessService = new java.util.ArrayList<org.uddi.api_v3.BusinessService>();
        _saveBusiness_bodyBusinessEntityVal1BusinessServices.getBusinessService().addAll(_saveBusiness_bodyBusinessEntityVal1BusinessServicesBusinessService);
        _saveBusiness_bodyBusinessEntityVal1.setBusinessServices(_saveBusiness_bodyBusinessEntityVal1BusinessServices);
        org.uddi.api_v3.IdentifierBag _saveBusiness_bodyBusinessEntityVal1IdentifierBag = new org.uddi.api_v3.IdentifierBag();
        java.util.List<org.uddi.api_v3.KeyedReference> _saveBusiness_bodyBusinessEntityVal1IdentifierBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
        _saveBusiness_bodyBusinessEntityVal1IdentifierBag.getKeyedReference().addAll(_saveBusiness_bodyBusinessEntityVal1IdentifierBagKeyedReference);
        _saveBusiness_bodyBusinessEntityVal1.setIdentifierBag(_saveBusiness_bodyBusinessEntityVal1IdentifierBag);
        org.uddi.api_v3.CategoryBag _saveBusiness_bodyBusinessEntityVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
        java.util.List<org.uddi.api_v3.KeyedReference> _saveBusiness_bodyBusinessEntityVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
        _saveBusiness_bodyBusinessEntityVal1CategoryBag.getKeyedReference().addAll(_saveBusiness_bodyBusinessEntityVal1CategoryBagKeyedReference);
        java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _saveBusiness_bodyBusinessEntityVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
        _saveBusiness_bodyBusinessEntityVal1CategoryBag.getKeyedReferenceGroup().addAll(_saveBusiness_bodyBusinessEntityVal1CategoryBagKeyedReferenceGroup);
        _saveBusiness_bodyBusinessEntityVal1.setCategoryBag(_saveBusiness_bodyBusinessEntityVal1CategoryBag);
        java.util.List<org.w3._2000._09.xmldsig.SignatureType> _saveBusiness_bodyBusinessEntityVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
        _saveBusiness_bodyBusinessEntityVal1.getSignature().addAll(_saveBusiness_bodyBusinessEntityVal1Signature);
        _saveBusiness_bodyBusinessEntityVal1.setBusinessKey("BusinessKey933461515");
        _saveBusiness_bodyBusinessEntity.add(_saveBusiness_bodyBusinessEntityVal1);
        _saveBusiness_body.getBusinessEntity().addAll(_saveBusiness_bodyBusinessEntity);
        org.uddi.api_v3.BusinessDetail _saveBusiness__return = port.saveBusiness(_saveBusiness_body);
        System.out.println("saveBusiness.result=" + _saveBusiness__return);


        }
        {
        System.out.println("Invoking getRegisteredInfo...");
        org.uddi.api_v3.GetRegisteredInfo _getRegisteredInfo_body = new org.uddi.api_v3.GetRegisteredInfo();
        _getRegisteredInfo_body.setAuthInfo("AuthInfo-2142265114");
        org.uddi.api_v3.InfoSelection _getRegisteredInfo_bodyInfoSelection = org.uddi.api_v3.InfoSelection.VISIBLE;
        _getRegisteredInfo_body.setInfoSelection(_getRegisteredInfo_bodyInfoSelection);
        org.uddi.api_v3.RegisteredInfo _getRegisteredInfo__return = port.getRegisteredInfo(_getRegisteredInfo_body);
        System.out.println("getRegisteredInfo.result=" + _getRegisteredInfo__return);


        }
        {
        System.out.println("Invoking saveBinding...");
        org.uddi.api_v3.SaveBinding _saveBinding_body = new org.uddi.api_v3.SaveBinding();
        _saveBinding_body.setAuthInfo("AuthInfo2130482020");
        java.util.List<org.uddi.api_v3.BindingTemplate> _saveBinding_bodyBindingTemplate = new java.util.ArrayList<org.uddi.api_v3.BindingTemplate>();
        org.uddi.api_v3.BindingTemplate _saveBinding_bodyBindingTemplateVal1 = new org.uddi.api_v3.BindingTemplate();
        java.util.List<org.uddi.api_v3.Description> _saveBinding_bodyBindingTemplateVal1Description = new java.util.ArrayList<org.uddi.api_v3.Description>();
        _saveBinding_bodyBindingTemplateVal1.getDescription().addAll(_saveBinding_bodyBindingTemplateVal1Description);
        org.uddi.api_v3.AccessPoint _saveBinding_bodyBindingTemplateVal1AccessPoint = new org.uddi.api_v3.AccessPoint();
        _saveBinding_bodyBindingTemplateVal1AccessPoint.setValue("Value-1904437966");
        _saveBinding_bodyBindingTemplateVal1AccessPoint.setUseType("UseType1542345314");
        _saveBinding_bodyBindingTemplateVal1.setAccessPoint(_saveBinding_bodyBindingTemplateVal1AccessPoint);
        org.uddi.api_v3.HostingRedirector _saveBinding_bodyBindingTemplateVal1HostingRedirector = new org.uddi.api_v3.HostingRedirector();
        _saveBinding_bodyBindingTemplateVal1HostingRedirector.setBindingKey("BindingKey1272892611");
        _saveBinding_bodyBindingTemplateVal1.setHostingRedirector(_saveBinding_bodyBindingTemplateVal1HostingRedirector);
        org.uddi.api_v3.TModelInstanceDetails _saveBinding_bodyBindingTemplateVal1TModelInstanceDetails = new org.uddi.api_v3.TModelInstanceDetails();
        java.util.List<org.uddi.api_v3.TModelInstanceInfo> _saveBinding_bodyBindingTemplateVal1TModelInstanceDetailsTModelInstanceInfo = new java.util.ArrayList<org.uddi.api_v3.TModelInstanceInfo>();
        _saveBinding_bodyBindingTemplateVal1TModelInstanceDetails.getTModelInstanceInfo().addAll(_saveBinding_bodyBindingTemplateVal1TModelInstanceDetailsTModelInstanceInfo);
        _saveBinding_bodyBindingTemplateVal1.setTModelInstanceDetails(_saveBinding_bodyBindingTemplateVal1TModelInstanceDetails);
        org.uddi.api_v3.CategoryBag _saveBinding_bodyBindingTemplateVal1CategoryBag = new org.uddi.api_v3.CategoryBag();
        java.util.List<org.uddi.api_v3.KeyedReference> _saveBinding_bodyBindingTemplateVal1CategoryBagKeyedReference = new java.util.ArrayList<org.uddi.api_v3.KeyedReference>();
        _saveBinding_bodyBindingTemplateVal1CategoryBag.getKeyedReference().addAll(_saveBinding_bodyBindingTemplateVal1CategoryBagKeyedReference);
        java.util.List<org.uddi.api_v3.KeyedReferenceGroup> _saveBinding_bodyBindingTemplateVal1CategoryBagKeyedReferenceGroup = new java.util.ArrayList<org.uddi.api_v3.KeyedReferenceGroup>();
        _saveBinding_bodyBindingTemplateVal1CategoryBag.getKeyedReferenceGroup().addAll(_saveBinding_bodyBindingTemplateVal1CategoryBagKeyedReferenceGroup);
        _saveBinding_bodyBindingTemplateVal1.setCategoryBag(_saveBinding_bodyBindingTemplateVal1CategoryBag);
        java.util.List<org.w3._2000._09.xmldsig.SignatureType> _saveBinding_bodyBindingTemplateVal1Signature = new java.util.ArrayList<org.w3._2000._09.xmldsig.SignatureType>();
        _saveBinding_bodyBindingTemplateVal1.getSignature().addAll(_saveBinding_bodyBindingTemplateVal1Signature);
        _saveBinding_bodyBindingTemplateVal1.setBindingKey("BindingKey-1600722769");
        _saveBinding_bodyBindingTemplateVal1.setServiceKey("ServiceKey780024880");
        _saveBinding_bodyBindingTemplate.add(_saveBinding_bodyBindingTemplateVal1);
        _saveBinding_body.getBindingTemplate().addAll(_saveBinding_bodyBindingTemplate);
        org.uddi.api_v3.BindingDetail _saveBinding__return = port.saveBinding(_saveBinding_body);
        System.out.println("saveBinding.result=" + _saveBinding__return);


        }

        System.exit(0);
    }

}
